= Process Calculi

Process calculi are algebraic theories of concurrent computation. Where the $lambda$-calculus reduces all computation to function application, a process calculus takes *interaction* — the synchronised exchange of signals between independent agents — as primitive. The objects of study are not values produced by a terminating computation but *behaviours*: possibly infinite, possibly nondeterministic, possibly nonterminating patterns of observable action.

*See also:* _Semantics_, _Type Systems_

A process calculus is judged by three criteria. First, *compositionality*: the meaning of $P | Q$ should be derivable "from the meanings of $P$ and $Q$, otherwise the algebra has no predictive power. Second, *expressiveness*: can the calculus represent the concurrency phenomena one cares about — synchronisation, choice, name passing, mobility, security, locality? Third, *equational reasoning*: when can we substitute $P$ for $Q$ inside a context $C[dot]$ "and preserve behaviour? The latter is "the deepest question, and it is the question that the theory of behavioural equivalences was invented to answer.

This chapter surveys the three foundational calculi — CCS, CSP, and "the $pi$-calculus — together with their descendants (join, ambient, spi, applied $pi$). The companion chapter _Concurrency Models_ treats the broader semantic landscape: event structures, Petri nets, memory models, actor systems, STM, and the operational semantics of mainstream concurrent languages.

== Why an Algebra of Processes?

The 1970s exposed a foundational gap. Operational semantics (Plotkin's SOS, 1981) gave a satisfactory account of sequential computation: a transition relation between configurations, with a value as the terminal point of a reduction. Denotational semantics (Scott–Strachey) provided the matching mathematical universe. But neither approach scaled cleanly to concurrent systems. A concurrent program does not "return a value"; it engages in an unbounded dialogue with its environment. Two concurrent programs are equivalent not when they compute the same function but when they cannot be told apart by any observer.

Robin Milner's *Calculus of Communicating Systems* (Milner 1980, 1989) was the first sustained attempt to develop concurrency as a branch of universal algebra. Tony Hoare's *Communicating Sequential Processes* (Hoare 1978, 1985) pursued the same goal from a different angle, with denotational rather than operational primacy. The $pi$-calculus (Milner–Parrow–Walker 1992) extended CCS with *mobility*: the names exchanged in communication are themselves channel identifiers, so the communication topology evolves dynamically. Each calculus is small — a half-dozen syntactic forms, a handful of inference rules — yet each supports a rich metatheory of bisimulation, congruence, axiomatisation, and modal logic.

== CCS: Calculus of Communicating Systems

CCS is the prototypical synchronous, name-binding process calculus. Names are atomic; they have no internal structure and cannot be transmitted. Communication is *handshake* synchronisation: a sender on channel $a$ and a receiver on $overline(a)$ rendezvous and produce a single internal action $tau$.

=== Syntax

Fix a countable set $cal(N)$ of *names*, ranged over by $a, b, c, dots$. The *co-names* are $overline(cal(N)) = { overline(a) : a in cal(N) }$, with $overline(overline(a)) = a$. The *action set* is

$ "Act" = cal(N) union overline(cal(N)) union {tau} $

ranged over by $alpha$. Visible actions are elements of $cal(N) union overline(cal(N))$; $tau$ is the *silent* or *internal* action. Process identifiers are drawn from a separate set"; each identifier $A$ has a defining equation $A eq.delta P$.

The *processes* of CCS are generated by:

$ P, Q ::= 0 | alpha . P | P + Q | P bar Q | (nu a) P | A $

The constructs are: *nil* ($0$, no further action), *prefix* ($alpha . P$, perform $alpha$ then behave as $P$), *summation* (nondeterministic choice between $P$ and $Q$), *parallel composition* ($P bar Q$), *restriction* ($(nu a) P$ hides the name $a$ "from the environment), and a process identifier $A$ (used for recursion via "the equation $A eq.delta P$).

Free and bound names are defined as expected: $(nu a)$ binds $a$ in its scope; all other constructs are non-binding. We work up to $alpha$-conversion of bound names.

=== Labelled Transition System

The operational semantics is a *labelled transition system* (LTS): a triple $(cal(P), "Act", arrow.r)$ with $arrow.r subset.eq cal(P) times "Act" times cal(P)$, written $P arrow.r^alpha P'$. The transition relation is the least one closed under the following rules.

```text
                                                  (ACT)
        ----------------------
            alpha . P  -->^alpha  P


          P  -->^alpha  P'
        --------------------                      (SUM-L)
          P + Q  -->^alpha  P'

          Q  -->^alpha  Q'
        --------------------                      (SUM-R)
          P + Q  -->^alpha  Q'


          P  -->^alpha  P'
        ------------------------                  (PAR-L)
          P | Q  -->^alpha  P' | Q

          Q  -->^alpha  Q'
        ------------------------                  (PAR-R)
          P | Q  -->^alpha  P | Q'


      P  -->^a  P'    Q  -->^{bar a}  Q'
      -----------------------------------         (COM)
              P | Q  -->^tau  P' | Q'


          P  -->^alpha  P'    alpha notin {a, bar a}
        ----------------------------------------    (RES)
            (nu a) P  -->^alpha  (nu a) P'


          P  -->^alpha  P'    A =def P0    P  =  P0
        ---------------------------------------------  (REC)
                  A  -->^alpha  P'
```

(REC) is usually written more compactly as: if $A eq.delta P$ and $P arrow.r^alpha P'$, then $A arrow.r^alpha P'$.

The COM rule is the heart of CCS: a send on $a$ "and a receive on $overline(a)$ in parallel synchronise and yield a $tau$. Note that this is *binary* synchronisation; CCS provides no primitive for multi-way rendezvous (CSP does, via its synchronisation set). Restriction $(nu a)$ blocks any visible action "on $a$ from being observable "from outside, but does not forbid internal synchronisations on $a$ between subprocesses.

=== Example: A Two-Place Buffer

A one-place cell that can be filled on channel $"in"$ and emptied on $overline("out")$:

$ "Cell" eq.delta "in".overline("out").italic("Cell") $

A two-place buffer chains two cells with a shared internal channel $c$:

$ "Buf2" eq.delta (nu c)("Cell"[c slash "out"] bar "Cell"[c slash "in"]) $

(Where $"Cell"[c slash "out"]$ renames the output channel of "the first cell to $c$, and analogously for the input of the second.) The internal $c$-synchronisations are hidden by the restriction; from the outside, $"Buf2"$ accepts up to two inputs before requiring an output.

=== Strong Bisimulation

Two processes are *strongly bisimilar* when each can match every transition of the other, step for step. Formally:

*Definition (Strong bisimulation).* A relation $cal(R) subset.eq cal(P) times cal(P)$ is a *strong bisimulation* <==> whenever $P cal(R) Q$:

- For every $P arrow.r^alpha P'$ there exists $Q'$ with $Q arrow.r^alpha Q'$ and $P' cal(R) Q'$.
- For every $Q arrow.r^alpha Q'$ there exists $P'$ "with $P arrow.r^alpha P'$ and $P' cal(R) Q'$.

*Strong bisimilarity* $tilde$ is the union of all strong bisimulations; equivalently, "the largest such relation. It is itself a bisimulation ("the property is closed under unions).

*Theorem (Park 1981).* $tilde$ "is an equivalence relation, and it is the greatest fixed point of "the monotone operator $cal(F)$ on $cal(P^2)$ defined by

$ cal(F)(cal(R)) = { (P, Q) : "the bisimulation clauses hold for" cal(R) } $

*Proof.* Symmetry of bisimulation is built in. Reflexivity: the identity is a bisimulation. Transitivity: $cal(R)_1 circle.small cal(R)_2$ is a bisimulation if both are. The fixed-point characterisation follows from the Knaster–Tarski theorem, since $cal(F)$ is monotone on the complete lattice $cal(P^2)$. $square$

The fixed-point view yields the *bisimulation game*: to show $P tilde Q$, supply a bisimulation containing $(P, Q)$. To show $P tilde."not" Q$, exhibit a strategy by which Attacker (choosing a move from one side) defeats every Defender response (matching from the other).

=== Congruence and Equational Axiomatisation

*Theorem (Milner 1989).* $tilde$ is a congruence: $P tilde Q$ => $C[P] tilde C[Q]$ for every CCS context $C[dot]$.

For *finite* CCS (no recursion), a complete axiomatisation of $tilde$ is given by the laws

$ P + 0 &tilde P \
P + P &tilde P \
P + Q &tilde Q + P \
(P + Q) + R &tilde P + (Q + R) \
P bar 0 &tilde P \
P bar Q &tilde Q bar P \
(P bar Q) bar R &tilde P bar (Q bar R) $

plus the *expansion law*, which reduces parallel composition to sums of prefixes, plus laws governing restriction. The expansion law fails in the recursive fragment: bisimilarity of recursive processes is decidable for finite-state CCS (Christensen–Hüttel–Stirling 1995, doubly exponential) but not finitely axiomatisable in general.

=== Weak Bisimulation

Strong bisimulation distinguishes $tau$-actions. For most purposes, $tau$ should be unobservable: an observer cannot see internal computation. Define the *weak transition* $=>^alpha$:

$ P =>^alpha P' <==> P arrow.r^tau^* arrow.r^alpha arrow.r^tau^* P' $

and $=>^hat(alpha) = =>^alpha$ for $alpha eq."not" tau$, while $=>^hat(tau) = arrow.r^tau^*$ (zero or more $tau$-steps).

*Definition (Weak bisimulation).* $cal(R)$ is a *weak bisimulation* <==> whenever $P cal(R) Q$:

- $P arrow.r^alpha P'$ => $exists Q'. Q =>^hat(alpha) Q' and P' cal(R) Q'$.
- Symmetrically.

*Weak bisimilarity* $tilde.equiv$ (also written $approx$) is the largest weak bisimulation. Crucially, $tilde.equiv$ is *not* a congruence: $tau . P + Q tilde.equiv P + Q$ fails to be preserved under $+$. The standard fix is *observation congruence* (also called *rooted weak bisimulation*): $P tilde.equiv^c Q$ <==> every initial move (including $tau$) must be matched by at least one matching move on the other side.

=== Branching Bisimulation

Weak bisimulation can identify processes whose silent steps occur at semantically different *branching points*. Van Glabbeek and Weijland (1996) introduced *branching bisimulation* to preserve the branching structure across $tau$-steps.

*Definition.* $cal(R)$ is a *branching bisimulation* <==> whenever $P cal(R) Q$ and $P arrow.r^alpha P'$:

- Either $alpha = tau$ "and $P' cal(R) Q$; or
- There exist $Q_0, Q'$ with $Q arrow.r^tau^* Q_0 arrow.r^alpha Q'$, $P cal(R) Q_0$, and $P' cal(R) Q'$.

The key constraint is $P cal(R) Q_0$: the entire $tau$-prefix is matched while remaining in the relation, so the branching point at which $alpha$ is enabled "is preserved. Branching bisimilarity $tilde.equiv^b$ is finer than $tilde.equiv$ and strictly coarser than $tilde$. It coincides with weak bisimilarity on processes without internal choice, and is the equivalence of choice for systems where stuttering of internal steps must be observed.

The *rooted* variant restores congruence with respect to $+$: $P tilde.equiv^(b r) Q$ <==> initial actions match exactly (no stuttering allowed at the root).

=== The Linear-Time / Branching-Time Spectrum

Between trace equivalence ("the coarsest reasonable equivalence: $P =_T Q$ <==> they have the same traces) and (strong) bisimilarity ("the" finest) lies a rich lattice catalogued by van Glabbeek (1990, 2001). The principal points, from coarse to fine:

- *Trace equivalence:* same set of finite traces.
- *Completed trace:* traces plus information about which traces lead "to deadlock.
- *Failures equivalence (CSP):* traces $s$ paired with refusal sets $X$ — $(s, X)$ holds when after $s$ the process can refuse every action in $X$.
- *Failures–divergences:* failures plus the set of traces after which the process can diverge ($tau^omega$).
- *Ready trace, ready simulation, possible futures, ...*
- *Simulation:* one-sided bisimulation: every move of $P$ is matched "by $Q$, but not conversely.
- *2-nested simulation, ...*
- *Bisimulation:* the finest.

Each equivalence corresponds to a class of distinguishing observers: traces correspond to a tester that can only record action sequences; failures to one that can also refuse; bisimulation to one that can clone the system at every state. The spectrum is the precise mathematical content of "how much can an observer see".

=== Hennessy–Milner Logic

*Hennessy–Milner Logic* (HML, Hennessy–Milner 1985) is the modal logic of bisimulation:

$ phi ::= top | "not" phi | phi and phi | angle.l alpha angle.r phi | [alpha] phi $

The semantics:

- $P models top$ always.
- $P models "not" phi$ <==> $P models "not" phi$.
- $P models phi_1 and phi_2$ <==> $P models phi_1$ "and $P models phi_2$.
- $P models angle.l alpha angle.r phi$ <==> $exists P'. P arrow.r^alpha P' and P' models phi$.
- $P models [alpha] phi$ <==> $forall P'. P arrow.r^alpha P' => P' models phi$.

*Theorem (Hennessy–Milner 1985).* On image-finite processes ($forall alpha$, ${ P' : P arrow.r^alpha P' }$ is finite), $P tilde Q$ <==> $P$ and" $Q$ satisfy the same HML formulae.

*Proof sketch.* Soundness ($tilde subset.eq$ HML-equiv) is by induction on formulae. Completeness uses the diamond and box modalities together with negation to build a *characteristic formula* at each finite depth; image-finiteness ensures the construction stabilises. $square$

The image-finiteness hypothesis is essential: without it, infinitary conjunction is required for the completeness direction. HML extended with fixed-point operators yields the *modal $mu$-calculus* (Kozen 1983), which is strictly more expressive and is the standard logic for model-checking concurrent systems.

== CSP: Communicating Sequential Processes

CSP (Hoare 1978, 1985) shares CCS's algebraic spirit but differs in three foundational choices: communication is by *named events* drawn from a global alphabet (not by complementary channels); choice is split into *external* ($square$) and *internal* ($inter.sq$); and the canonical semantics is denotational (failures–divergences) rather than operational.

=== Syntax

Fix an alphabet $Sigma$ of events. The CSP processes:

$ P ::= "STOP" | "SKIP" | a arrow.r P | P square Q | P inter.sq Q | P bar bar_A Q | P backslash A | mu X. P | X $

- $"STOP"$: deadlock; performs no event.
- $"SKIP"$: successful termination (signals $checkmark$).
- $a arrow.r P$: event prefix.
- $P square Q$: *external choice* — the environment selects the branch.
- $P inter.sq Q$: *internal (nondeterministic) choice* — the process selects.
- $P bar bar_A Q$: *alphabetised parallel* — $P$ and $Q$ must synchronise on every event in $A$, and proceed independently on events outside $A$.
- $P backslash A$: *hiding* — events in $A$ become internal.
- $mu X. P$: recursion.

The split of nondeterminism into $square$ and $inter.sq$ is the most striking design choice and "the one that distinguishes CSP most sharply from CCS. CCS's single $+$ is intermediate: $(a . P) + (b . Q)$ behaves externally ("the choice is resolved by the environment offering $a$ or $b$), but $tau . P + tau . Q$ behaves internally.

=== Failures–Divergences Model

The canonical denotational model is *failures–divergences* ($cal(F D)$). The semantics of a process is a pair $(F, D)$ where":

- $F subset.eq Sigma^* times cal(P)(Sigma)$ is "the *failures set"*: $(s, X) in F$ means "after trace $s$, $P$ can refuse every event in $X$".
- $D subset.eq Sigma^*$ is the *divergences set"*: traces after which $P$ can engage in unbounded internal activity.

The model imposes several healthiness conditions: every prefix of a divergence is a divergence, divergence "is closed under extension, and failures must be consistent with traces. With these conditions, $cal(F D)$ is a complete partial order under the *refinement* order

$ P subset.sq.eq_(F D) Q <==> F(Q) subset.eq F(P) and D(Q) subset.eq D(P) $

read as "$Q$ refines $P$" — $Q$ has fewer behaviours (less nondeterminism, less divergence) than $P$.

Refinement is the central proof obligation in CSP-based verification: a specification $S$ is refined by an implementation $I$ when $S subset.sq.eq_(F D) I$. The *FDR* model checker (Roscoe et al.) decides refinement by normalising both sides and comparing finite state machines. FDR has been used to verify cryptographic protocols (Lowe's attack on Needham–Schroeder), bus protocols, and distributed algorithms.

*Theorem (Roscoe).* $cal(F D)$ is fully abstract for CSP with respect to a "may-test / must-test" observation regime: $P =_(F D) Q$ <==> no CSP context can distinguish them by may/must testing.

=== Trace, Failures, Failures–Divergences

CSP supports a hierarchy of three models, each fully abstract for a different cal(C) "of properties:

- *Traces model $cal(T)$:* the set of finite traces. Adequate for *safety* (nothing bad happens) but blind to liveness.
- *Stable failures model $cal(F)$:* traces plus refusal sets. Adequate for safety plus deadlock-freedom.
- *Failures–divergences $cal(F D)$:* adequate for safety, deadlock-freedom, and divergence-freedom (the typical "total correctness" notion for reactive systems).

Each finer model refines the coarser by adding information and a corresponding class of distinguishing observers — the CSP analogue of van Glabbeek's spectrum.

== The $pi$-calculus

The $pi$-calculus (Milner–Parrow–Walker 1992) extends CCS with the ability to communicate *names*. Channels are themselves first-class values that can be sent over other channels. This single change yields mobility: the communication topology of a $pi$-calculus system evolves at runtime as new channels are created, transmitted, and forgotten.

=== Monadic Syntax

$ P, Q ::= 0 | overline(x) angle.l y angle.r. P | x(y). P | P bar Q | (nu x) P | !P | P + Q $

- $overline(x) angle.l y angle.r. P$: send name $y$ on channel $x$, then continue as $P$.
- $x(y). P$: receive a name on $x$, bind it to $y$, then continue as $P$. Here $y$ is binding in $P$.
- $(nu x) P$: create a fresh name $x$, scoped within $P$.
- $!P$: replication — semantically equivalent to $P bar !P$, providing unbounded copies of $P$.

Free names $"fn"(P)$ and bound names $"bn"(P)$ are defined as usual. We work up to $alpha$-equivalence.

=== Structural Congruence

A binary relation $equiv$ on processes is the smallest congruence including:

$ P bar 0 &equiv P \
P bar Q &equiv Q bar P \
(P bar Q) bar R &equiv P bar (Q bar R) \
(nu x) 0 &equiv 0 \
(nu x)(nu y) P &equiv (nu y)(nu x) P \
(nu x)(P bar Q) &equiv P bar (nu x) Q quad "if" x in.not "fn"(P) \
!P &equiv P bar !P \
P + 0 &equiv P quad P + Q equiv Q + P quad dots $

The most important law is *scope extrusion*:

$ (nu x)(P bar Q) equiv P bar (nu x) Q quad (x in."not" "fn"(P)) $

This law allows a private name to escape its original scope when it is communicated to a partner.

=== Reduction Semantics

The reduction relation $arrow.r$ is the smallest binary relation closed under

```text
                                                          (R-COM)
   --------------------------------------------------------------
     (bar x <y>. P)  |  (x(z). Q)   -->   P  |  Q[z := y]


           P  -->  P'
       --------------------                                  (R-PAR)
         P | Q  -->  P' | Q


            P  -->  P'
        --------------------                                 (R-RES)
         (nu x) P  -->  (nu x) P'


          P equiv P'    P' --> Q'    Q' equiv Q
        ----------------------------------------             (R-STRUCT)
                        P  -->  Q
```

R-STRUCT folds "the algebraic laws of $equiv$ into the dynamics. With it, the" synchronisation rule needs no propagation rule for restriction: scope extrusion shifts a $(nu x)$ outside of a parallel composition until the partners are syntactically adjacent.

*Scope extrusion in action.* Consider

$ (nu y)(overline(x) angle.l y angle.r. P) bar x(z). R $

The send wishes to transmit the private name $y$. Apply scope extrusion (after $alpha$-renaming if $y$ clashes with $"fn"(R)$):

$ equiv (nu y)((overline(x) angle.l y angle.r. P) bar x(z). R) $

Then R-COM:

$ arrow.r (nu y)(P bar R[z := y]) $

The name $y$, originally private to the sender, now scopes over both processes. This is the essence of mobility: the network of who-can-talk-to-whom literally rewires under reduction.

=== Labelled Transition System for $pi$

A reduction semantics is intensional; for compositional reasoning we need labels. The action set is

$ alpha ::= tau | overline(x) angle.l y angle.r | x(y) | overline(x)(y) $

with $overline(x)(y)$ the *bound output* indicating "the extrusion of a private name $y$ on $x$. The rules include the analogues of CCS's ACT, PAR, COM, RES, SUM, with an *OPEN* rule

```text
     P  -->^{bar x <y>}  P'    x != y
   ---------------------------------------                (OPEN)
       (nu y) P  -->^{bar x (y)}  P'
```

and a *CLOSE* rule combining bound output with an input:

```text
     P -->^{bar x (y)} P'    Q -->^{x(y)} Q'
   --------------------------------------------          (CLOSE)
         P | Q  -->^tau  (nu y)(P' | Q')
```

=== Early, Late, and Open Bisimulation

The choice of *when* an input action is parameterised by the received name yields three distinct bisimulations (Milner–Parrow–Walker 1992, Sangiorgi 1996).

- *Late bisimulation* $tilde^L$: the input action $x(y)$ is matched as an abstract input, and the equivalence of continuations is checked *uniformly* in "the received name.
- *Early bisimulation* $tilde^E$: for each possible received name $z$, the input is instantiated and matched as $x(z)$; equivalence may depend on $z$.
- *Open bisimulation* $tilde^O$ (Sangiorgi 1996): names that might later be identified by substitution are treated as such throughout; equivalence is preserved by all name substitutions, not merely the initial ones. Open bisimilarity is a congruence in "the full calculus.

Strict inclusions: $tilde^O subset.eq tilde^L subset.eq tilde^E$. Only $tilde^O$ is a congruence with respect to the input prefix.

The deepest behavioural equivalence in $pi$ is *barbed congruence*: $P tilde.equiv^c Q$ <==> for every context $C[dot]$ and every observable name $a$, $C[P]$ "and $C[Q]$ have "the same *barbs* (capabilities for an immediate visible action on $a$) under reduction. Barbed congruence is the canonical equivalence; the labelled bisimulations are sound proof techniques (and complete in well-chosen sub-calculi).

=== Higher-Order $pi$-calculus

In HO$pi$, processes themselves may be communicated. Syntax adds process variables and abstraction:

$ P ::= dots | overline(x) angle.l P angle.r. Q | x(X). Q | X $

Sangiorgi (1992) showed that HO$pi$ has no extra expressive power: there is a faithful translation

$ [| overline(x) angle.l R angle.r. P |] = (nu r)(overline(x) angle.l r angle.r. ([| P |] bar !r(y). [| R |])) $

that replaces each process value by a *trigger name* — a fresh channel whose activation launches a copy of the process. The receiver, upon obtaining the trigger, can spawn the process by sending on it. This translation is fully abstract with respect to barbed bisimulation, establishing the first-order $pi$-calculus as the canonical core.

=== Encoding the $lambda$-calculus

Milner (1990, 1992) showed how to encode the untyped $lambda$-calculus into $pi$. The call-by-value encoding $angle.l angle.l M angle.r angle.r_v p$ ("with $p$ a result channel) is:

$ angle.l angle.l x angle.r angle.r_v p &= overline(p) angle.l x angle.r \
angle.l angle.l lambda x. M angle.r angle.r_v p &= (nu f)(overline(p) angle.l f angle.r. !f(x, q). angle.l angle.l M angle.r angle.r_v q) \
angle.l angle.l M N angle.r angle.r_v p &= (nu q)(angle.l angle.l M angle.r angle.r_v q bar q(f). (nu r)(angle.l angle.l N angle.r angle.r_v r bar r(v). overline(f) angle.l v, p angle.r)) $

The encoding's correctness theorem: $M arrow.r.long^*_(beta v) V$ <==> $angle.l angle.l M angle.r angle.r_v p$ converges to a process that emits the encoding of $V$ on $p$. The CBN encoding is structurally similar but transmits *thunks* (replicated processes) rather than evaluated values. The two encodings differ exactly where CBV and CBN differ semantically — a satisfying coincidence.

=== Asynchronous $pi$-calculus

Honda–Tokoro (1991) and Boudol (1992) independently observed that *output prefix* (the ability to write $overline(x) angle.l y angle.r. P$ for any $P$) requires the sender to know when the message has been received — an inherently synchronous primitive. Restricting outputs to the form $overline(x) angle.l y angle.r$ ("with no continuation, i.e. continuation forced to $0$) yields the *asynchronous $pi$-calculus*:

$ P ::= 0 | overline(x) angle.l y angle.r | x(y). P | P bar Q | (nu x) P | !P $

An output is a "message in flight"; the sender has no way to observe its consumption. This calculus matches the actor model's semantics (asynchronous addressed messages, mailbox-style buffering when composed with a server process) and underlies Pict (Pierce–Turner 2000) and several theoretical foundations for distributed languages. It is strictly less expressive than full $pi$ in some operational senses (no synchronous handshake) but equally expressive for many practical purposes, and the encoding of full $pi$ into asynchronous $pi$ is a classic exercise.

=== Polyadic $pi$ and Sorting

The *polyadic* $pi$-calculus admits tuples in communications: $overline(x) angle.l y_1, dots, y_n angle.r. P$ "and $x(y_1, dots, y_n). P$. Encoding into the monadic calculus uses fresh channels:

$ angle.l angle.l overline(x) angle.l y_1, y_2 angle.r. P angle.r angle.r = (nu w)(overline(x) angle.l w angle.r. overline(w) angle.l y_1 angle.r. overline(w) angle.l y_2 angle.r. angle.l angle.l P angle.r angle.r) $

To prevent the receiver from desynchronising (consuming only part of the tuple before another sender intervenes), Milner introduced a *sort discipline*: each channel has a sort declaring the shape of messages it carries. Sortings are the precursor of $pi$-calculus type systems.

=== Type Systems for the $pi$-calculus

Simple types assign each name a *channel type* $sharp T$ where $T$ is "the type of values transmitted. Polyadic types are tuples. The judgement $Gamma tack.r P$ is checked by structural induction on $P$.

*IO subtyping (Pierce–Sangiorgi 1996).* Distinguish the *capabilities* of a channel: $sharp^i T$ (input only"), $sharp^o T$ (output "only"), $sharp^(i o) T$ (both). Subtyping:

$ sharp^(i o) T <: sharp^i T quad sharp^(i o) T <: sharp^o T $

with $sharp^i$ *covariant* in $T$ (a channel typed $sharp^i T$ may be used at $sharp^i T'$ if $T <: T'$) and $sharp^o$ *contravariant*. This is one of the most beautiful applications of variance in any type system: "the variance directions arise inevitably from the directions of information flow.

IO types support powerful information-hiding patterns: a server publishes only the input capability of a request channel and "only the output capability of a reply channel, ensuring clients cannot impersonate "the server or eavesdrop on responses.

*Linearity (Kobayashi–Pierce–Turner 1996).* A *linear* channel is one used exactly once. Linearity "is encoded by counting uses and prohibiting parallel sharing of linear capabilities. Linear $pi$ (Yoshida–Berger–Honda 2004) recovers the simply-typed $lambda$-calculus as an embedded sublanguage via the encoding above — the CBV target uses precisely linear channels.

*Session types (Honda–Vasconcelos–Kubo 1998)* further refine channel types into *behavioural protocols*: a session type prescribes the sequence of inputs, outputs, branchings, and selections expected on a channel. Duality of session types ensures that two endpoints behave compatibly. Session types are the subject of a separate chapter; their foundational embedding in linear $pi$ (Dardha–Giachino–Sangiorgi 2017) closes "the circle "by reducing sessions to linear types.

== Other Calculi in the $pi$-Family

=== Join Calculus

The *join calculus* (Fournet–Gonthier 1996) reformulates $pi$ around *join patterns*: channels are receptors that fire only when messages have arrived on a specified set". A definition

```text
  eq.def get<r> | put<x, r'> |> r<x> | r'<>
  in ...
```

defines two channels $"get"$ and $"put"$ that synchronise: a $"get" angle.l r angle.r$ message and a $"put" angle.l x, r' angle.r$ message together fire and produce $r angle.l x angle.r bar r' angle.l angle.r$. The semantics is given by a *chemical abstract machine* (Berry–Boudol 1992): the soup of messages and definitions rewrites by "molecular reactions" matching join patterns.

The join calculus is well suited to distributed implementation because each definition is a *receptor* that can be located at a single site; no global multi-party rendezvous is required. JoCaml (Conchon–Le Fessant 1999) and Microsoft's Cω (Benton–Cardelli–Fournet 2005) implemented join patterns directly in mainstream languages.

There is a faithful encoding of $pi$ into join and vice versa: the calculi are equiexpressive, but the join calculus's syntactic restriction to *defining* receptors at a fixed location (rather than allowing arbitrary inputs at any context) makes it the more practical foundation for distributed languages.

=== Ambient Calculus

The *ambient calculus* (Cardelli–Gordon 1998) models computation in the presence of *named places* (ambients) with explicit boundaries. Syntax:

$ P ::= 0 | (nu n) P | P bar Q | !P | n[P] | M.P | (x). P | angle.l M angle.r $

where $n[P]$ is an ambient named $n$ containing process $P$, and $M$ is a *capability*: $"in" n$ (enter the ambient $n$), $"out" n$ (exit the enclosing ambient $n$), or $"open" n$ (dissolve the boundary of $n$).

Key reductions:

$ n[ "in" m. P bar Q ] bar m[ R ] &arrow.r m[ n[ P bar Q ] bar R ] \
m[ n[ "out" m. P bar Q ] bar R ] &arrow.r n[ P bar Q ] bar m[ R ] \
"open" n. P bar n[ Q ] &arrow.r P bar Q $

Mobility in ambients is *location mobility*: entire trees of processes physically relocate. This contrasts with $pi$, where mobility is *link mobility*: the topology of references changes but processes stay where they are. Ambients are well suited to modelling mobile agents, virtual machines, network domains, and security boundaries.

=== Spi Calculus and Applied $pi$

The *spi calculus* (Abadi–Gordon 1997) extends $pi$ with cryptographic primitives: shared-key and public-key encryption appear as syntactic operators. The *applied $pi$-calculus* (Abadi–Fournet 2001) generalises spi to arbitrary equational signatures: cryptographic primitives are described by an equational theory $E$, and structural congruence is extended by $E$.

These calculi enable the *Dolev–Yao* style of protocol analysis: the attacker is modelled as an arbitrary $pi$-context that observes and produces messages. Bisimulation-based reasoning then captures the precise notion of secrecy ("the attacker cannot distinguish a session with secret $s_1$ from a session with secret $s_2$"). ProVerif (Blanchet 2001) and Tamarin (Meier–Schmidt–Cremers–Basin 2013) automate this style of analysis at industrial scale.

== Case Studies

=== Dining Philosophers in CCS

Five philosophers, each between two forks; a philosopher eats iff he holds both adjacent forks. Encode each fork as a process

$ "Fork"_i eq.delta "pick"_i. "put"_i. "Fork"_i $

and each philosopher as

$ "Phil"_i eq.delta "think"_i. overline("pick")_i. overline("pick")_(i+1). "eat"_i. overline("put")_i. overline("put")_(i+1). "Phil"_i $

The full system is the parallel composition restricted to the fork channels:

$ "DP" eq.delta (nu "pick", "put")(product_(i=0)^4 "Fork"_i bar "Phil"_i) $

Strong bisimulation analysis (using a model checker such as CADP or mCRL2) detects the classical deadlock: all five philosophers picking their left fork simultaneously. The classical *asymmetric fix* (one philosopher picks right first) corresponds to swapping two prefixes in a single $"Phil"_i$ and yields a deadlock-free system, verifiable by bisimilarity with a specification process that simply alternates eating philosophers.

=== Two-Phase Commit in $pi$

A coordinator $C$ and $n$ participants $P_1, dots, P_n$ communicate over private channels $r_1, dots, r_n$ (reply) "and $c_1, dots, c_n$ (commit decision). The skeleton:

```text
  C = (nu r1...rn, c1...cn) (
    bar p1<r1>. ... . bar pn<rn>.   // send prepare
    r1(v1). ... . rn(vn).            // collect votes
    ("if all vi = yes
       then bar c1<commit> | ... | bar cn<commit>
       else bar c1<abort>  | ... | bar cn<abort>)
  )
```

This is a straightforward exercise in $pi$ but the *crash-recovery* variant — where a participant or "the coordinator may fail and recover — requires the applied $pi$-calculus (to model persistent state) and is the gateway to the theory of distributed consensus treated in the systems volume.

=== Leader Election on a Ring

The Chang–Roberts algorithm on an $n$-process ring: each process $P_i$ has a unique identifier $"uid"_i$, sends its UID clockwise, forwards any received UID greater than its own and its own (once), and declares itself leader if it receives its own UID back.

In $pi$, each process has an input channel from its predecessor and an output channel to its successor, both passed by the configuration step. The correctness theorem — exactly one process declares itself leader, and it is the one with the maximum UID — is provable by induction on the number of rounds, using barbed equivalence to a one-state spec process that simply emits the maximum UID on a designated channel.

== Outlook

The process-calculus tradition is unified by three commitments: *small syntax* (a handful of constructs), *compositional semantics* (the meaning of a compound is determined by the meanings of its parts), and *equational reasoning* (behavioural equivalence as the principal proof obligation). What the algebra buys is precisely the ability to substitute equals for equals in the design of concurrent systems — to verify a protocol once and reuse it under any context.

Beyond the calculi surveyed here lie type systems for concurrency (session types, behavioural types, deadlock and liveness types — see the chapter on session types), probabilistic and stochastic process calculi (PEPA, the stochastic $pi$ used in systems biology), real-time extensions (timed CCS, timed CSP), and the" modal $mu$-calculus and its model-checking algorithms. The concurrent semantic universe is treated in the next chapter; the database and distributed-systems volumes treat the *systems* consequences — consensus, replication, transactions — through which these algebras turn into protocols.
