= System F and Parametricity

System F — the *polymorphic $lambda$-calculus*, or second-order $lambda$-calculus — extends the simply-typed $lambda$-calculus with quantification over types. Discovered independently by Jean-Yves Girard (1971, thesis 1972) as a tool to prove the consistency of second-order Peano arithmetic, and rediscovered by John Reynolds (1974) as the type system underlying polymorphic programming, System F is the bridge between proof theory and modern functional language design.

*See also:* _Simply-Typed Lambda Calculus_, _Type Systems_, _Dependent Types_, _Categorical Semantics_

This chapter develops System F in full. We give the syntax, typing rules with T-TABS and T-TAPP, and worked Church encodings of $"Bool"$, $"Nat"$, $"Pair"$, and $"List"$ as polymorphic types. We show why the $Y$-combinator is not typable. We sketch Girard's strong-normalization proof via *reducibility candidates*, the genuine innovation over Tait's plain reducibility predicates. We develop Reynolds' *abstraction theorem* (parametricity) and Wadler's "theorems for free", deriving in detail the free theorems for the polymorphic identity, swap, and map types. We treat existential types and Mitchell–Plotkin abstract data types. We climb to System $F_omega$ and the Barendregt cube. We close with Wells' undecidability of System F type inference and Pierce's undecidability of full $F_{<:}$.

== Syntax

*Types.*
$ tau ::= alpha | tau_1 arrow.r tau_2 | forall alpha. tau $

where $alpha, beta, gamma, ...$ range over a countably infinite set of *type variables*. The quantifier $forall alpha. tau$ binds $alpha$ in $tau$. We work up to $alpha$-equivalence of bound type variables.

*Terms* (Church presentation).
$ e ::= x | lambda x : tau . e | e_1 space e_2 | Lambda alpha . e | e [tau] $

Two new term-formers: the *type abstraction* $Lambda alpha . e$ (binds the type variable $alpha$ in the body $e$) and *type application* $e[tau]$ (instantiates the type variable bound by $Lambda$ at $tau$). Greek capital $Lambda$ is used at the term level; lowercase $lambda$ remains for ordinary abstraction.

*Free type variables.* Defined by mutual recursion with free term variables. Notation $"FTV"(tau)$ and $"FTV"(e)$:
$ "FTV"(alpha) &= {alpha} \
"FTV"(tau_1 arrow.r tau_2) &= "FTV"(tau_1) union "FTV"(tau_2) \
"FTV"(forall alpha. tau) &= "FTV"(tau) \\ {alpha} $

A *kinding judgment* $Delta tack.r tau$ (where $Delta$ is a finite set of type variables) certifies that $"FTV"(tau) subset.eq Delta$. In $F_omega$ this becomes a richer judgment $Delta tack.r tau : kappa$ where $kappa$ is a *kind* (see below).

*Capture-avoiding type substitution.* $[alpha |-> sigma] tau$ behaves exactly like term substitution, $alpha$-renaming bound type variables as needed.

== Static Semantics

The typing judgment is $Delta; Gamma tack.r e : tau$, where $Delta$ tracks type variables in scope and $Gamma$ tracks term variables. We write $Delta; Gamma$ as $Gamma$ when $Delta$ is clear.

```text
  x : tau in Gamma
  --------------------                       (T-VAR)
  Delta; Gamma |- x : tau

  Delta |- tau_1   Delta; Gamma, x : tau_1 |- e : tau_2
  ------------------------------------------------------   (T-ABS)
  Delta; Gamma |- lam x : tau_1. e : tau_1 -> tau_2

  Delta; Gamma |- e_1 : tau_1 -> tau_2    Delta; Gamma |- e_2 : tau_1
  ------------------------------------------------------------------    (T-APP)
  Delta; Gamma |- e_1 e_2 : tau_2

  Delta, alpha; Gamma |- e : tau              (alpha not in Delta, FTV(Gamma))
  --------------------------------------                                  (T-TABS)
  Delta; Gamma |- Lam alpha. e : forall alpha. tau

  Delta; Gamma |- e : forall alpha. tau     Delta |- sigma
  ---------------------------------------------------------               (T-TAPP)
  Delta; Gamma |- e [sigma] : [alpha |-> sigma] tau
```

The side condition in T-TABS — that $alpha$ does not occur in $Gamma$ — is the analogue of the universal-introduction *eigenvariable* condition in natural deduction. Without it, one could derive $x : alpha tack.r Lambda alpha . x : forall alpha . alpha$, a contradiction in the Curry–Howard reading.

*Lemma (Type Substitution).* If $Delta, alpha; Gamma tack.r e : tau$ and $Delta tack.r sigma$, then $Delta; [alpha |-> sigma] Gamma tack.r [alpha |-> sigma] e : [alpha |-> sigma] tau$.

*Lemma (Inversion).* If $Delta; Gamma tack.r Lambda alpha . e : rho$, then $rho = forall alpha. tau$ with $Delta, alpha; Gamma tack.r e : tau$. If $Delta; Gamma tack.r e [sigma] : rho$, then $Delta; Gamma tack.r e : forall alpha. tau$ with $rho = [alpha |-> sigma] tau$ for some $tau$.

== Dynamic Semantics

Reduction is generated by two redex schemes:
$ (lambda x : tau . e_1) space e_2 &arrow.r_beta [x |-> e_2] e_1 space space space space space (beta) \
(Lambda alpha . e) [sigma] &arrow.r_beta [alpha |-> sigma] e space space space space space (beta_2) $

The second is *type-level $beta$* — instantiating a polymorphic value at a type. Both rules are subject to congruence (compatible closure).

*Theorem (Subject Reduction).* If $Delta; Gamma tack.r e : tau$ and $e arrow.r e'$, then $Delta; Gamma tack.r e' : tau$.

*Proof.* Induction on the reduction. The $beta_2$ case uses the Type Substitution Lemma. $square$

== Examples and Church Encodings

=== The Polymorphic Identity

$ "id" = Lambda alpha . lambda x : alpha . x : forall alpha . alpha arrow.r alpha $

Instantiation: $"id" ["Int"] : "Int" arrow.r "Int"$; $"id" [forall beta . beta arrow.r beta] : (forall beta . beta arrow.r beta) arrow.r (forall beta . beta arrow.r beta)$. The second is the famous *impredicative* instantiation — $"id"$ applied at its *own* type. This is the source of System F's expressive power and the source of its proof-theoretic strength: the second-order quantifier ranges over a universe that includes the type being defined.

=== Booleans

$ "Bool" &:= forall alpha . alpha arrow.r alpha arrow.r alpha \
"true"  &:= Lambda alpha . lambda x : alpha . lambda y : alpha . x \
"false" &:= Lambda alpha . lambda x : alpha . lambda y : alpha . y \
"if" b space "then" space e_1 "else" space e_2 &:= b [tau] space e_1 space e_2 $

where $tau$ is the common type of $e_1, e_2$. Verify: $"if" "true" "then" 3 "else" 5 = ("true"["Int"]) space 3 space 5 = 3$. The Boolean *eliminator* is just type instantiation followed by application.

=== Natural Numbers (Church Numerals)

$ "Nat" &:= forall alpha . (alpha arrow.r alpha) arrow.r alpha arrow.r alpha \
overline(0) &:= Lambda alpha . lambda f : alpha arrow.r alpha . lambda x : alpha . x \
overline(n+1) &:= Lambda alpha . lambda f : alpha arrow.r alpha . lambda x : alpha . f^(n+1) (x) \
"succeeds" &:= lambda n : "Nat" . Lambda alpha . lambda f : alpha arrow.r alpha . lambda x : alpha . f (n [alpha] space f space x) \
"add"  &:= lambda m n : "Nat" . Lambda alpha . lambda f : alpha arrow.r alpha . lambda x : alpha . m [alpha] space f space (n [alpha] space f space x) \
"mul"  &:= lambda m n : "Nat" . Lambda alpha . lambda f : alpha arrow.r alpha . m [alpha] space (n [alpha] space f) $

Iteration is *built in*: $n [tau] space s space z$ applies $s$ to $z$ exactly $n$ times.

*Theorem.* The functions $"Nat" arrow.r "Nat"$ representable in System F are exactly the *provably total recursive functions* of second-order Peano arithmetic — a strictly larger cal(C) than those provable in $"PA"$ (Girard 1972). This includes Ackermann's function and many beyond.

=== Pairs

$ "Pair" alpha beta &:= forall gamma . (alpha arrow.r beta arrow.r gamma) arrow.r gamma \
"pair" &:= Lambda alpha beta . lambda x : alpha . lambda y : beta . Lambda gamma . lambda k : alpha arrow.r beta arrow.r gamma . k space x space y \
"fst"  &:= Lambda alpha beta . lambda p : "Pair" alpha beta . p [alpha] (lambda x : alpha . lambda y : beta . x) \
"snd"  &:= Lambda alpha beta . lambda p : "Pair" alpha beta . p [beta] (lambda x : alpha . lambda y : beta . y) $

Verify $"fst" ["Int", "Bool"] ("pair" ["Int", "Bool"] space 3 space "true") arrow.r^* 3$.

=== Lists

$ "List" alpha &:= forall beta . (alpha arrow.r beta arrow.r beta) arrow.r beta arrow.r beta \
"nil"         &:= Lambda alpha . Lambda beta . lambda c : alpha arrow.r beta arrow.r beta . lambda n : beta . n \
"cons"        &:= Lambda alpha . lambda h : alpha . lambda t : "List" alpha . \
                  &space space Lambda beta . lambda c : alpha arrow.r beta arrow.r beta . lambda n : beta . c space h space (t [beta] space c space n) $

A list *is* its own fold: $"foldr" c space n space ell = ell [beta] space c space n$. The representation is naturally a *Böhm–Berarducci* encoding (Böhm–Berarducci 1985), and it generalises to all strictly-positive inductive types.

=== Existentials (Anticipating §)

Church-encoded $exists alpha . tau$ as $forall beta . (forall alpha . tau arrow.r beta) arrow.r beta$ — see the existentials section below.

== Strong Normalization (Girard 1972)

*Theorem (Girard 1972).* Every well-typed term of System F is strongly normalising.

This is *substantially* harder than the STLC case. The naïve attempt — define $cal(R)_tau$ by induction on $tau$, with $cal(R)_(forall alpha . tau) = sect.big_(sigma) [alpha |-> ?] cal(R)_(tau)$ — fails because the type $sigma$ may be larger than $forall alpha . tau$ itself (impredicativity!), so no structural induction on types is available. Tait's plain reducibility works for STLC but breaks here.

Girard's solution: *reducibility candidates*. The idea is to *give up* on defining $cal(R)$ directly and instead axiomatize a *family* of acceptable interpretations. A type variable $alpha$ is interpreted by *any* candidate satisfying the closure conditions; $forall alpha . tau$ then quantifies semantically over all candidates.

=== Reducibility Candidates

A set $cal(C)$ of closed terms of a given type is a *candidate* (write $cal(C) in "CR"_tau$) iff:
- *(CR1)* Every $e in cal(C)$ is strongly normalising.
- *(CR2)* If $e in cal(C)$ and $e arrow.r e'$, then $e' in cal(C)$.
- *(CR3)* If $e$ is *neutral* (not a $lambda$- or $Lambda$-abstraction) and every $e'$ with $e arrow.r e'$ lies in $cal(C)$, then $e in cal(C)$.

*Note.* CR3 implies that every candidate contains all *strongly-neutral normal forms* (variables, applications to normal forms with neutral head). In particular candidates are nonempty.

*Notational difference from STLC.* In Girard's framework, the *interpretation* $[| tau |]_eta in "CR"$ is parameterised by an *environment* $eta$ assigning to each free type variable a candidate. Define it by recursion on $tau$:
$ [| alpha |]_eta &= eta(alpha) \
[| tau_1 arrow.r tau_2 |]_eta &= {e : forall e' in [| tau_1 |]_eta . space e space e' in [| tau_2 |]_eta} \
[| forall alpha . tau |]_eta &= sect.big_(cal(C) in "CR") space [| tau |]_(eta, alpha |-> cal(C)) $

The big intersection is the crux. Because we range over the *abstract* class of candidates rather than concrete types, the recursion is on $tau$ rather than on the (semantic) type of the interpretation.

*Lemma.* For every type $tau$ and environment $eta$, $[| tau |]_eta in "CR"$.

*Proof.* Induction on $tau$. Variables: by assumption $eta(alpha) in "CR"$. Arrow: verify CR1, CR2, CR3 directly; CR3 uses that $e space e'$ is neutral when $e$ is, plus IH. Universal: an intersection of candidates is a candidate (intersect the closure conditions pointwise). $square$

*Substitution Lemma.* $[| [alpha |-> sigma] tau |]_eta = [| tau |]_(eta, alpha |-> [| sigma |]_eta)$.

*Main Theorem.* If $Delta; Gamma tack.r e : tau$, then for every type-environment $eta$ assigning candidates to $Delta$, and every closing substitution $gamma$ with $gamma(x) in [| Gamma(x) |]_eta$ for each $x$, we have $gamma(e) in [| tau |]_eta$.

*Proof.* Induction on the typing derivation.
- T-VAR: by assumption.
- T-APP: by definition of arrow candidate.
- T-ABS: analogue of the STLC Abstraction Lemma, using CR3 to handle the redex case; $beta$-step reaches the IH.
- T-TAPP: by Substitution Lemma, $gamma(e)[sigma] in [| forall alpha . tau' |]_eta subset.eq [| tau' |]_(eta, alpha |-> [| sigma |]_eta) = [| [alpha |-> sigma] tau' |]_eta$, modulo the fact that type application is itself neutral and reduces via $beta_2$ — handled by CR3.
- T-TABS: for every candidate $cal(C)$ and the extended environment, show $gamma(e) in [| tau |]_(eta, alpha |-> cal(C))$ by IH; conclude $Lambda alpha . gamma(e) in [| forall alpha . tau |]_eta$. The reduction $(Lambda alpha . gamma(e)) [sigma] arrow.r [alpha |-> sigma] gamma(e)$ is the $beta_2$-redex, handled by an analogue of the Abstraction Lemma. $square$

*Corollary.* Take $eta(alpha) = "SN"_alpha$ and $gamma(x_i) = x_i$ (variables are in every candidate by CR3). Then $e in [| tau |]_eta$, hence $e$ is SN by CR1. $square$

=== Why Plain Reducibility Fails

In STLC, $cal(R)_tau$ was defined by induction on $tau$. In System F we cannot do the same for $forall alpha . tau$: defining it as $sect_sigma cal(R)_([alpha |-> sigma] tau)$ would require already having $cal(R)$ at *every* type $sigma$ — including types *larger* than $forall alpha . tau$. The recursion is non-well-founded. Girard's solution decouples the *type* from its *interpretation*: candidates are an axiomatic class, not constructed by induction on syntax. The price is a slightly more elaborate proof; the prize is SN for all of System F.

== The $Y$-Combinator is Not Typable

The untyped fixed-point combinator
$ Y = lambda f . (lambda x . f (x space x)) (lambda x . f (x space x)) $
satisfies $Y space f arrow.r^* f (Y space f)$ and produces non-terminating reductions. If $Y$ were typable at some type $tau = (alpha arrow.r alpha) arrow.r alpha$ in System F, then for $f : alpha arrow.r alpha$, $Y space f$ would be a closed well-typed term of type $alpha$. By Strong Normalization, $Y space f$ is SN. But $Y space f$ reduces to $f (Y space f)$ which reduces to $f (f (Y space f))$ etc., infinite reduction — contradiction. Hence no fixed-point combinator is typable in System F. Adding $"fix"$ as a primitive (with its own typing rule $forall alpha . (alpha arrow.r alpha) arrow.r alpha$ and reduction rule) makes the system Turing-complete but destroys SN and logical consistency.

== Reynolds' Parametricity

*The intuition.* A function of type $forall alpha . alpha arrow.r alpha$ knows nothing about $alpha$; the only thing it can do with its argument is return it. Hence the only inhabitant is (up to $beta eta$) the identity. Reynolds (1983) formalised this slogan via a relational interpretation, generalising the candidate construction.

=== The Relational Interpretation

For each type $tau$ and each *relation environment* $rho$ assigning to each type variable $alpha$ a relation $rho(alpha) : A_alpha <-> B_alpha$ between two sets, define a binary relation $[| tau |]_rho : [| tau |]_(rho_1) <-> [| tau |]_(rho_2)$:

$ [| alpha |]_rho &= rho(alpha) \
[| tau_1 arrow.r tau_2 |]_rho &= {(f, g) : forall (a, b) in [| tau_1 |]_rho . space (f space a, g space b) in [| tau_2 |]_rho} \
[| forall alpha . tau |]_rho &= {(p, q) : forall A B . forall R : A <-> B . space (p[A], q[B]) in [| tau |]_(rho, alpha |-> R)} $

The first projection $rho_1(alpha) = A_alpha$, second $rho_2(alpha) = B_alpha$; for $tau_1 arrow.r tau_2$, $[| tau_1 arrow.r tau_2 |]_(rho_1) = [| tau_1 |]_(rho_1) arrow.r [| tau_2 |]_(rho_1)$.

*Theorem (Reynolds 1983, Abstraction).* For every closed term $emptyset tack.r e : tau$ and every relation environment $rho$, the pair $([| e |]_(rho_1), [| e |]_(rho_2)) in [| tau |]_rho$. In particular if $e$ is closed and $rho$ has all $rho(alpha) = $ identity, the theorem says $e$ is related to itself — *every term respects every parametric relation*.

*Proof.* Induction on the typing derivation, exactly mirroring the SN proof but with binary relations in place of candidates. $square$

== Theorems for Free (Wadler 1989)

Reynolds' abstraction theorem yields immediate free theorems derivable from the type alone, without inspecting the implementation.

=== Free Theorem for $forall alpha . alpha arrow.r alpha$

Take a closed $i : forall alpha . alpha arrow.r alpha$. By parametricity with relation $R = {(a, a') : a' = h(a)}$ — the graph of an arbitrary function $h : A arrow.r B$ — we get $(i[A], i[B]) in [| alpha arrow.r alpha |]_(alpha |-> R)$, i.e., for every $a : A$, $(i[A] space a, i[B] space (h space a)) in R$, i.e., $i[B] (h space a) = h (i[A] space a)$. So $i$ is *natural* in $alpha$.

Specialising $A = B = "Unit"$, $h = "id"$: $i["Unit"] : "Unit" arrow.r "Unit"$ takes $()$ to $()$. Then by the naturality square instantiated at $A = "Unit"$, $h(()) = a$ for arbitrary $a : B$: $i[B] space a = h (i["Unit"] ()) = h(()) = a$. Hence $i[B] = "id"_B$ for every $B$, so $i = Lambda alpha . lambda x . x$ extensionally.

*Conclusion.* Up to $beta eta$, the *only* inhabitant of $forall alpha . alpha arrow.r alpha$ is the identity.

=== Free Theorem for $forall alpha . "List" alpha arrow.r "List" alpha$

Take $r : forall alpha . "List" alpha arrow.r "List" alpha$. Specialising the abstraction theorem at the graph of $h : A arrow.r B$, we get for every list $"xs" : "List" A$:
$ r[B] ("map" h space "xs") = "map" h space (r[A] space "xs") $

So $r$ *commutes with $"map"$*. This holds for *every* function $r$ of that type: $"reverse"$, $"tail"$ (when defined), $"filter" p$ (no — $p$ depends on $alpha$), but uniform list-permutations and prefix-droppers.

=== Free Theorem for $forall alpha . alpha times alpha arrow.r alpha$

Take $f : forall alpha . alpha times alpha arrow.r alpha$. Specialising at $R = {((a_1, a_2), b) : b = a_1} union {((a_1, a_2), b) : b = a_2}$ (the disjoint-union relation): by parametricity, $f[B] (b, b) = b$ — diagonal. More carefully, take $R$ to be the graph of $h$ as before; then $f[B] (h space a_1, h space a_2) = h (f[A] (a_1, a_2))$.

Now pick $A = "Bool"$, $a_1 = "true"$, $a_2 = "false"$, $B = "Bool"$, $h = "id"$: $f["Bool"] ("true", "false") in {"true", "false"}$. By a case analysis using $h = $ constant function, we can show $f$ is *either* uniformly $pi_1$ *or* uniformly $pi_2$. (Detailed argument: define $h_1 (x) = "true"$ when $x = a_1$ else "false"; the naturality square forces a binary choice.)

*Conclusion.* The only inhabitants of $forall alpha . alpha times alpha arrow.r alpha$ are $pi_1$ and $pi_2$.

=== Free Theorem for $forall alpha beta . (alpha arrow.r beta) arrow.r "List" alpha arrow.r "List" beta$

Take such a $m$. The free theorem says: for every $f : A_1 arrow.r B_1$, $g : A_2 arrow.r B_2$, $h_alpha : A_1 arrow.r A_2$, $h_beta : B_1 arrow.r B_2$ with $h_beta circle.small f = g circle.small h_alpha$, we have $"map" h_beta circle.small m[A_1, B_1] f = m[A_2, B_2] g circle.small "map" h_alpha$. Setting $h_alpha = "id"$, $g = h_beta circle.small f$ yields $"map" (h_beta circle.small f) space "xs" = "map" h_beta (m[A_1, B_1] f space "xs")$, i.e., $m$ is *functorial* (preserves identity is similar). Wadler's slogan: *every polymorphic list-mapping function is up to $beta eta$ equal to $"map" f$ followed by some permutation/dropping that is independent of $f$* — but for the type $forall alpha beta . (alpha arrow.r beta) arrow.r "List" alpha arrow.r "List" beta$ specifically, by also requiring the relational input $f$ to vary, we get that $m = "map"$ (up to $beta eta$).

=== Implications

Parametricity is not merely a curiosity: it underlies *representation independence* (abstract types are not exposed by polymorphic clients), *foldr-build fusion* (Gill–Launchbury–Peyton Jones 1993), and the *Yoneda lemma* in functor land. It also fails dramatically when the language has *non-parametric* features: `typecase`, runtime type representations, `seq` (which observes evaluation), and reference cells all break parametricity.

== Existential Types and Abstract Data Types

Mitchell–Plotkin (1988) recognised that *existential types* model abstract data types. The Church-encoding:
$ exists alpha . tau &:= forall beta . (forall alpha . tau arrow.r beta) arrow.r beta \
"pack" tau "with" e "as" exists alpha . tau' &:= Lambda beta . lambda k : forall alpha . tau' arrow.r beta . k [tau] space e \
"unpack" angle.l alpha, x angle.r = e "in" e' &:= e [tau_("answer")] (Lambda alpha . lambda x : tau' . e') $

The introduction $"pack"$ packages a *concrete* witness $tau$ together with a value $e : [alpha |-> tau] tau'$, hiding the witness behind the existential. The elimination $"unpack"$ binds a *star.op* type variable $alpha$ (the abstract type) and a term variable $x$ of representation type $tau'$. Crucially, the eliminator's body $e'$ may not mention $alpha$ in its result type — this is *information hiding*.

*Example.* A counter ADT:
$ "Counter" &:= exists alpha . alpha times (alpha arrow.r alpha) times (alpha arrow.r "Int") \
"intCounter" &:= "pack" "Int" "with" (0, lambda x . x + 1, lambda x . x) "as" "Counter" $

Clients see only $alpha$, never `Int`. They can $"init"$, $"incr"$, and $"read"$, but not — by parametricity! — exploit the representation.

*Parametricity gives ADT abstraction.* Two implementations of $"Counter"$ are observationally equivalent <==> related by a *simulation* $R$ (a relation between the two representation types respecting init/incr/read). This is the formal content of *representation independence* (Reynolds 1983; Mitchell 1986).

== System $F_omega$: Higher Kinds

System $F_omega$ adds *type-level functions*. The grammar becomes layered:

*Kinds.* $kappa ::= * | kappa_1 arrow.r kappa_2$.

*Type constructors.* $tau ::= alpha | tau_1 arrow.r tau_2 | forall alpha : kappa . tau | lambda alpha : kappa . tau | tau_1 space tau_2$.

The two new type-formers $lambda alpha : kappa . tau$ and $tau_1 space tau_2$ allow type-level abstraction and application. A *type-level* $beta$-conversion is added:
$ (lambda alpha : kappa . tau) space sigma arrow.r_beta [alpha |-> sigma] tau $

A *kind judgment* $Delta tack.r tau : kappa$ ensures well-formedness:

```text
  alpha : kappa in Delta                       Delta |- tau_1 : *    Delta |- tau_2 : *
  ---------------------- (K-VAR)               ---------------------------------------- (K-ARROW)
  Delta |- alpha : kappa                       Delta |- tau_1 -> tau_2 : *

  Delta, alpha : kappa |- tau : *              Delta, alpha : kappa_1 |- tau : kappa_2
  --------------------------------- (K-ALL)    ------------------------------------------- (K-TLAM)
  Delta |- forall alpha : kappa. tau : *       Delta |- lam alpha : kappa_1. tau : kappa_1 -> kappa_2

  Delta |- tau_1 : kappa_1 -> kappa_2    Delta |- tau_2 : kappa_1
  ---------------------------------------------------------------- (K-TAPP)
  Delta |- tau_1 tau_2 : kappa
```

Types of kind $*$ are *proper* types (inhabited by terms). Types of higher kinds are *type operators* — type-level functions.

*Examples.*
- $"List" : * arrow.r *$ — a type operator taking a type to a type.
- $"State" : * arrow.r * arrow.r *$ — state transformer.
- $"Functor" : (* arrow.r *) arrow.r *$? — well, in Haskell `Functor` is a type *class*, but the underlying constructor maps a functor (kind $* arrow.r *$) to a constraint (kind `Constraint`).

The type equality used in T-APP, T-TAPP is now equality *modulo type-level $beta eta$* — this is decidable (type-level reduction is SN by the same candidate argument lifted one level), but the type checker must perform conversion.

*Theorem (Girard 1972).* $F_omega$ is strongly normalising at both the term and type levels.

== The Barendregt Cube

Barendregt (1991) organised the family of pure type systems into a *cube* indexed by three binary axes — the four kinds of dependency allowed:

#table(
  columns: (auto, auto, auto, auto),
  [*System*], [*Polymorphism (terms on types)*], [*Type operators (types on types)*], [*Dependent types (types on terms)*],
  [$lambda^arrow.r$ (STLC)], [no], [no], [no],
  [$lambda 2$ = System F], [*yes*], [no], [no],
  [$lambda omega$ = STLC + type ops], [no], [*yes*], [no],
  [$lambda omega 2$ = $F_omega$], [*yes*], [*yes*], [no],
  [$lambda P$ = LF], [no], [no], [*yes*],
  [$lambda P 2$], [*yes*], [no], [*yes*],
  [$lambda P omega$], [no], [*yes*], [*yes*],
  [$lambda C$ = CoC], [*yes*], [*yes*], [*yes*],
)

Terms depending on terms (ordinary $lambda$) is always present. The three axes correspond to three of the four corners of the *Pure Type System* (PTS) classification. The apex $lambda C$ — the *Calculus of Constructions* (Coquand–Huet 1988) — is the foundation of Coq (see _Dependent Types_).

*Geometric picture.* Visualise as a cube with $lambda^arrow.r$ at the origin and $lambda C$ at the diagonally opposite corner; each axis is one dependency. F sits adjacent to STLC by one edge; $F_omega$ two edges; CoC three.

== Decidability and Type Inference

=== Hindley–Milner Decidability

The *let-polymorphic* restriction of System F (no first-cal(C) $forall$ in argument positions; quantifiers only at $"let"$-bindings) — *Hindley–Milner* (HM; Damas–Milner 1982) — has decidable type inference in near-linear time (see _Type Systems_). This is the type system of ML, OCaml, Haskell 98.

=== System F Type Inference is Undecidable

*Theorem (Wells 1999).* Type inference for full (Curry-style) System F is undecidable. Type *checking* with annotations on all $Lambda$ and $[tau]$ is decidable (just walk the tree); but inferring a type for an unannotated term is undecidable.

*Proof sketch.* Wells gave a reduction from *semi-unification* — given a system of equations $tau_i = tau'_i$ and inequations $tau_j lt.eq.eq tau'_j$ (where $lt.eq.eq$ is "is a substitution instance of"), decide solvability. Semi-unification is undecidable (Kfoury–Tiuryn–Urzyczyn 1990). Wells encoded an arbitrary semi-unification problem as a System F typability problem: each inequation becomes a quantifier instantiation. $square$

=== System $F_omega$ Type Checking is Decidable but Expensive

Type checking $F_omega$ is *decidable* — type equality requires deciding $beta eta$-equality of type expressions, which is decidable because type-level reduction is SN (Girard 1972). But the checking *cost* can be huge:

*Theorem (Henglein–Mairson 1991, Statman 1979).* Deciding $beta$-equality in $F_omega$ is *not* elementary recursive: the worst-case time is a tower of exponentials whose height depends on the term.

Practical type checkers (Haskell's GHC, OCaml) restrict to fragments where this blow-up does not arise; full $F_omega$ as a *type system* is rarely directly exposed.

== Bounded Quantification: $F_(<:)$

Cardelli and Wegner (1985) extended System F with *subtyping* by adding a bound to each quantifier:
$ tau ::= ... | forall alpha <: sigma . tau | "Top" $

The bounded universal $forall alpha <: sigma . tau$ ranges only over subtypes of $sigma$. Typing rules include T-TAPP requiring $sigma' <: sigma$ for instantiation. Subtyping $tau_1 <: tau_2$ is defined by the usual contravariance of arrows, etc.

Two variants:
- *Kernel $F_(<:)$* (Curien–Ghelli 1992): subtyping of $forall alpha <: sigma . tau$ requires *equal* bounds. Decidable.
- *Full $F_(<:)$*: subtyping of $forall alpha <: sigma_1 . tau_1 <: forall alpha <: sigma_2 . tau_2$ requires $sigma_2 <: sigma_1$ (contravariance in the bound). This is the natural reading; this is what programmers want.

*Theorem (Pierce 1994).* Subtype-checking in full $F_(<:)$ is *undecidable*.

*Proof sketch.* Pierce reduced the halting problem for *two-counter Minsky machines* to $F_(<:)$ subtype-checking. The trick: encode the configuration $(q, c_1, c_2)$ of a counter machine as a type; the subtyping query $tau_q <: tau_(q')$ holds <==> the machine, starting from $q$, eventually reaches a state included in $q'$. Counter increment is encoded by wrapping in a $forall$; counter decrement uses the contravariance of bounds. Each subtyping step in the recursion mimics one machine step. Termination of subtype-checking would decide halting — impossible.

Hence Pierce's recommendation: stick to *kernel* $F_(<:)$ or impose a syntactic restriction. The languages Java and C\# face similar issues with bounded generics: Java's wildcard subtyping is, technically, undecidable as well (Grigore 2017 showed Java generic subtype-checking is Turing-complete).

== Implementation Notes

```haskell
-- A toy System F type checker in Haskell
data Ty
  = TVar Int                 -- de Bruijn type variable
  | TArr Ty Ty
  | TAll Ty                  -- binder: TAll body
  deriving (Eq, Show)

data Tm
  = Var Int
  | Lam Ty Tm
  | App Tm Tm
  | TLam Tm                  -- big-lambda
  | TApp Tm Ty               -- type application
  deriving (Show)

-- Type-level shift: shift bound type vars by d when crossing k binders
shiftTy :: Int -> Int -> Ty -> Ty
shiftTy d k (TVar i)    | i >= k = TVar (i + d)
                        | otherwise = TVar i
shiftTy d k (TArr a b)  = TArr (shiftTy d k a) (shiftTy d k b)
shiftTy d k (TAll t)    = TAll (shiftTy d (k+1) t)

-- Substitute the topmost type variable with s
substTy :: Ty -> Ty -> Ty
substTy s = go 0
  where
    go k (TVar i)
      | i == k    = shiftTy k 0 s
      | i >  k    = TVar (i - 1)
      | otherwise = TVar i
    go k (TArr a b) = TArr (go k a) (go k b)
    go k (TAll t)   = TAll (go (k+1) t)

infer :: [Ty] -> Tm -> Either String Ty
infer ctx (Var i)
  | i < length ctx = Right (ctx !! i)
  | otherwise      = Left "unbound"
infer ctx (Lam ty body) = do
  bt <- infer (ty : ctx) body
  return (TArr ty bt)
infer ctx (App f a) = do
  ft <- infer ctx f
  at <- infer ctx a
  case ft of
    TArr d c | d == at -> Right c
    TArr d _           -> Left ("expected " ++ show d ++ ", got " ++ show at)
    _                  -> Left "not a function"
infer ctx (TLam body) = do
  -- Shift term-variable types' type-vars under the new binder
  bt <- infer (map (shiftTy 1 0) ctx) body
  return (TAll bt)
infer ctx (TApp e ty) = do
  et <- infer ctx e
  case et of
    TAll body -> Right (substTy ty body)
    _         -> Left "type application of non-forall"
```

A real-world System F implementation (e.g., GHC Core's `System FC`) extends with coercions (for type-equality witnesses) and data constructors, but the above is the essential skeleton.

== The Logical Reading

Under Curry–Howard, System F corresponds to *second-order intuitionistic propositional logic* — propositional logic with quantification over *propositions*. The slogan:

$ "Types in F" &<-> "Formulas in IPC"^2 \
"Terms in F" &<-> "Proofs in IPC"^2 \
"Strong normalization" &<-> "Cut elimination for IPC"^2 $

The fact that System F is SN is exactly the *Hauptsatz* (cut-elimination theorem) for second-order intuitionistic logic. Girard's original motivation (his thesis) was precisely this — to give a constructive consistency proof of second-order Peano arithmetic by encoding it in $F$ and proving SN.

*Conservativity over $"PA"_2$.* The functions $"Nat" arrow.r "Nat"$ representable in System F are exactly the *provably total* recursive functions of second-order arithmetic ($"PA"_2$). This is a *vast* class: it goes well beyond the primitive-recursive functions, the multiply-recursive functions, the $epsilon_0$-recursive functions of Gödel's System T. It includes any function provably total in *any* finite extension of PA by induction over predicates definable in second-order logic. Practical implication: *any* function you can reasonably want to compute is expressible in System F — but you can't always type-infer the encoding.

== Categorical Models of System F

The naïve set-theoretic interpretation does *not* work for System F: if $alpha$ ranges over all sets and $forall alpha . tau$ is interpreted as the product over all sets, the resulting set is too large to be a set. Reynolds (1984) proved:

*Theorem (Reynolds 1984).* There is no set-theoretic model of polymorphism — no model in which $forall alpha . tau$ is interpreted as the set-theoretic product over all sets and $Lambda$-abstraction by ordinary function-formation.

The standard models of System F therefore work in restricted categories:
- *PER models* (Bruce–Longo 1990): partial equivalence relations on a fixed combinatory algebra.
- *Domain-theoretic models* (Coquand–Gunter–Winskel 1989): inverse limit constructions in $omega$-CPOs.
- *Coherence spaces* (Girard 1986): the original semantic motivation for linear logic.
- *Realizability* (Longo–Moggi 1990): types as quotients of the natural numbers under realizability.

In every case, the semantic universe of "types" is a small object in some category, not the full collection of sets.

== Practical Languages and System F

- *Haskell*: GHC's intermediate language `System FC` is System $F_omega$ plus *coercions* (witnesses for type equalities arising from GADTs and type families).
- *OCaml*: surface ML is Hindley–Milner, but `let` polymorphism, first-cal(C) modules (`module type of`), and GADTs push toward System F.
- *Scala*: subtyping + higher kinds = essentially $F_(<:)^omega$. Decidability is precarious (Scala type-checking can loop).
- *Rust*: traits and lifetimes are an HM-like fragment with subtype-like coercions.
- *Java/C\#*: F-bounded generics. Subtype-checking undecidable in the limit (Grigore 2017 for Java).
- *Idris/Agda/Lean*: full dependent types — strictly beyond System F (see _Dependent Types_).

In every case the language designer chose a *fragment* that is either inferable (HM) or merely checkable (System FC). No production language requires the user to type-infer full System F.

== Worked Example: Fold-as-Type

The Church encoding of $"List" alpha$ as $forall beta . (alpha arrow.r beta arrow.r beta) arrow.r beta arrow.r beta$ *"is"* the fold operator: applying a list to $(c, n)$ is computing its right fold. So we can define:

```haskell
{-\# LANGUAGE RankNTypes \#-}

-- Church-encoded lists
newtype CList a = CList { unCL :: forall b. (a -> b -> b) -> b -> b }

nilC :: CList a
nilC = CList (\_ n -> n)

consC :: a -> CList a -> CList a
consC h t = CList (\c n -> c h (unCL t c n))

toList :: CList a -> [a]
toList xs = unCL xs (:) []

fromList :: [a] -> CList a
fromList = foldr consC nilC

-- Map for free, by the free theorem
mapC :: (a -> b) -> CList a -> CList b
mapC f xs = CList (\c n -> unCL xs (c . f) n)
```

The fact that `mapC` just works by composition with `f` is *parametricity in action*. No pattern matching is needed because the data structure carries its own eliminator.

== Equational Theory

System F enjoys $beta eta$-conversion at both term and type levels:
+ $(beta)$  $(lambda x : tau . e_1) space e_2 = [x |-> e_2] e_1$
+ $(beta_2)$ $(Lambda alpha . e) [sigma] = [alpha |-> sigma] e$
+ $(eta)$  $lambda x : tau . (e space x) = e$ if $x in."not" "FV"(e)$
+ $(eta_2)$ $Lambda alpha . (e [alpha]) = e$ if $alpha in."not" "FTV"(e)$

*Theorem.* $beta eta$-equality is *decidable* in System F (because SN + confluence).

In contrast: *contextual* equivalence (Mason–Talcott 1991) is decidable for STLC but undecidable for System F — even though *syntactic* $beta eta$ is decidable, the question "are $e_1$ and $e_2$ indistinguishable in *every* context" is harder, because contexts include type instantiations at types that may have rich inhabitants. Parametricity is a *partial* characterisation: contextual equivalence is at least as strong as parametric equivalence and conjecturally — but not provably in general — equal.

== More Free Theorems Worked in Detail

=== The Type $forall alpha . alpha$

A closed inhabitant $e : forall alpha . alpha$ would, instantiated at $"Empty"$, produce a closed term of type $"Empty"$ — contradicting consistency. By parametricity, $[| forall alpha . alpha |] = sect_R [| alpha |]_R = sect_R R$. The intersection over *all* relations of the empty relation is empty. Hence $forall alpha . alpha$ has no closed inhabitant — it is the *false* proposition under Curry–Howard.

=== The Type $forall alpha . alpha arrow.r alpha arrow.r alpha$

This is $"Bool"$ in Church encoding. The free theorem: for $b : forall alpha . alpha arrow.r alpha arrow.r alpha$, take $h : A arrow.r B$ as a graph relation; parametricity gives $b[B] (h space x) (h space y) = h (b[A] space x space y)$. Specialising as before forces $b$ to be either $Lambda alpha . lambda x y . x$ or $Lambda alpha . lambda x y . y$. Hence exactly two inhabitants, matching the Boolean intuition.

=== The Type $forall alpha . (alpha arrow.r "Bool") arrow.r "List" alpha arrow.r "List" alpha$

A $"filter"$-like type. The free theorem: for $f : forall alpha . (alpha arrow.r "Bool") arrow.r "List" alpha arrow.r "List" alpha$, every $h : A arrow.r B$ yields $f[B] (p circle.small "..." h^(-1) ?) ...$ — the technical formulation requires $h$ to be a function, $p_A = p_B circle.small h$, and yields $f[B] space p_B space ("map" h space "xs") = "map" h space (f[A] space p_A space "xs")$.

In words: filtering commutes with $"map"$ provided the predicate is appropriately transformed.

=== Continuation-Passing Types

The type $forall alpha . (A arrow.r alpha) arrow.r alpha$ for a fixed type $A$ is the *continuation* / *Yoneda* encoding. Parametricity says: every $k : forall alpha . (A arrow.r alpha) arrow.r alpha$ is of the form $Lambda alpha . lambda c : A arrow.r alpha . c space a$ for a unique $a : A$. The map $k |-> k[A] space "id"_A$ is a bijection between $forall alpha . (A arrow.r alpha) arrow.r alpha$ and $A$ — this is the *Yoneda lemma* in functor-free disguise.

Generalisation: $forall alpha . (A arrow.r alpha) arrow.r F alpha tilde.equiv F A$ for any *functor* $F$.

== Logical Relations as Proof Technique

Parametricity is the *binary* logical-relation construction. *Unary* logical relations are exactly Tait/Girard reducibility for SN. *Step-indexed* logical relations (Appel–McAllester 2001, Ahmed 2004) handle recursive types and mutable state by indexing relations by a *step count* — a relation $R_k$ guarantees behaviour up to $k$ reduction steps. Step-indexing is the bedrock of modern soundness proofs for ML-"with"-references (e.g., Iris, RustBelt).

A unifying meta-theorem: for any *open* term $Gamma tack.r e : tau$ and any logical relation $cal(L)$, if $cal(L)$ is closed under the typing rules, then $e$ respects $cal(L)$. This is the *fundamental lemma* of logical relations. SN, parametricity, contextual equivalence, type abstraction — all are instances.

== Operational Semantics Variants

=== CBV vs CBN in System F

The polymorphic identity $"id" = Lambda alpha . lambda x : alpha . x$ behaves identically under CBV and CBN: $"id" ["Int"] space (3 + 4)$ reduces to $3 + 4$ then $7$ (CBV) or to $3 + 4$ then $7$ (CBN). Type abstraction is *always* a value — $Lambda alpha . e$ does not evaluate $e$, by analogy with $lambda x . e$.

A subtle point in *predicative* extensions: when type instantiation triggers further reduction inside $e$, evaluation strategies matter. Practical systems (Haskell, OCaml) treat $Lambda alpha$ as type-erasable — it disappears at runtime.

=== Erasure

*Theorem (Mitchell, Girard, others).* A typed System F term $e$ and its *type-erasure* $|e|$ (delete all $Lambda$ and $[tau]$) have the same untyped reduction behaviour on the corresponding term-level redexes.

So a System F program *runs* like an untyped $lambda$ program — types are computationally inert. This justifies *type erasure* in compilers: GHC erases types between Core and STG/Cmm; OCaml erases at the back end. The exception: features like Haskell's `Typeable` or polymorphic recursion with type-cal(C) dictionaries pass *runtime representations*, breaking pure erasure.

== Predicative vs Impredicative System F

The defining feature of System F is *impredicativity*: $forall alpha . tau$ may be instantiated at $forall alpha . tau$ itself. This is what gives System F its proof-theoretic strength.

*Predicative System F* — restrict instantiation to types of lower *rank* — is strictly weaker. The Hindley–Milner system is the *rank-1* predicative restriction: quantifiers only at the outermost position, never in argument positions. *Rank-N polymorphism* (in GHC) allows quantifiers at any rank, requiring type annotations to be inferable.

```haskell
-- Rank-2 polymorphism
rank2 :: (forall a. a -> a) -> (Int, Bool)
rank2 f = (f 3, f True)

-- Cannot be written in rank-1 ML/HM
```

Rank-1 inference is decidable (HM); rank-$k$ inference for $k gt.eq 3$ is undecidable (Kfoury–Wells 1994); rank-2 is decidable but exponential in the worst case.

== Implementation: From System F to GHC Core

GHC's intermediate language *System FC* (Sulzmann–Chakravarty–Peyton Jones–Donnelly 2007) extends System F with *coercion variables* — runtime-free witnesses of type equalities arising from GADTs and type families. A term may carry a coercion $gamma : tau_1 tilde.eq tau_2$ and *cast* a value $e : tau_1$ to $e |> gamma : tau_2$. Coercions are themselves typed, with their own kind of arrow ($tilde.eq$), introduction (`refl`), and elimination (`sym`, `trans`, `nth`, `inst`).

System FC is *just* expressive enough to type-check what GHC's source can produce, and *just* simple enough to admit a reliable type checker. It is essentially System $F_omega$ + axioms; the type system itself is decidable (GHC's core type-checker is the *one* part of the compiler that is meant to be correctness-critical).

```haskell
-- GADT in source
data Eq a b where"
  Refl :: Eq a a

-- After translation: Refl carries a coercion variable
-- pattern match on Refl introduces the coercion into context
```

== Existentials in Practice

In Haskell, existential types are written via *forall in argument position*:

```haskell
{-\# LANGUAGE ExistentialQuantification \#-}

data Showable = forall a. Show a => MkShowable a

showIt :: Showable -> String
showIt (MkShowable x) = show x

zoo :: [Showable]
zoo = [MkShowable 42, MkShowable "hi", MkShowable True]
```

Here `Showable` is essentially `exists a. (Show a, a)`. The constraint `Show a` is part of the existential package — packed in, opened out. Such *heterogeneous lists* are a typical use of Haskell existentials.

In OCaml, *first-cal(C) modules* play a similar role:

```ocaml
module type SHOWABLE = sig
  type t
  val value : t
  val show : t -> string
end

let zoo : (module SHOWABLE) list = [
  (module struct type t = int let value = 42 let show = string_of_int end);
  (module struct type t = string let value = "hi" let show = fun s -> s end)
]
```

The module type *"is"* the existential; module values pack a concrete type with operations.

== Connection to Category Theory

System F has a beautiful interpretation in terms of *dinatural transformations*. A polymorphic function $f : forall alpha . F(alpha) arrow.r G(alpha)$, where $F, G$ are functors, corresponds to a *dinatural transformation* from $F$ to $G$. Parametricity is the statement that polymorphic terms are *automatically* dinatural — naturality holds for *free*.

Wadler's free theorems are dinaturality squares:
```text
       F(h)
  F(A) -----> F(B)
   |             |
f_A|             |f_B
   v             v
  G(A) -----> G(B)
       G(h)
```
commutes for every $h : A arrow.r B$ and every parametric $f$.

== Boxes, Stuckness, and Type Soundness for F

*Theorem.* If $emptyset; emptyset tack.r e : tau$ in System F, then either $e$ is a value or $e arrow.r e'$ for some $e'$.

*Proof.* Standard progress/preservation. Canonical forms: values of arrow type are $lambda$; of universal type are $Lambda$. $square$

Combined with strong normalization: evaluation of every closed well-typed term terminates in a value. *No* infinite computation; no run-time errors; no stuckness. System F is a *total* language. The trade-off, as for STLC, is incompleteness: not every algorithmically computable function is implementable in System F (only the second-order PA-provably-total ones).

== A Detailed Computation

Take $"id" = Lambda alpha . lambda x : alpha . x$ and the term
$ e = "id" [forall beta . beta arrow.r beta] space "id" $

By T-TAPP: $"id" [forall beta . beta arrow.r beta] : (forall beta . beta arrow.r beta) arrow.r (forall beta . beta arrow.r beta)$.
By T-APP applied to $"id" : forall beta . beta arrow.r beta$ (the second occurrence): well-typed.

Reduction:
+ $beta_2$: $"id" [forall beta . beta arrow.r beta] = lambda x : (forall beta . beta arrow.r beta) . x$.
+ $beta$: $(lambda x . x) space "id" arrow.r "id"$.

Final result: $"id"$ — as expected, identity applied to identity is identity. The *impredicative* instantiation $"id" [forall beta . beta arrow.r beta]$ is the key step: System F lets $"id"$ be applied at its *own* type, which is what makes the second-order quantifier truly powerful.

== Polymorphism and Type Erasure: Practical Compilation

Three strategies for compiling polymorphic code:

+ *Erasure* (OCaml, Haskell): polymorphism vanishes; all values share a uniform representation (boxed pointer). Type instantiation has no runtime cost.
+ *Specialization* (C++ templates, Rust generics, MLton ML): each instantiation generates a star.op specialized version. Fast but blows up code size.
+ *Dictionary passing* (Haskell type classes): polymorphism is preserved but type-cal(C) methods pass a runtime *dictionary* of operations.

Erasure relies on parametricity: by Reynolds, a polymorphic function cannot inspect its argument, so a uniform boxed representation suffices. Languages with *non-parametric* features (Haskell's `Typeable`, Java's reflection) break erasure and require runtime type information.

== Inductive Types via System F

Despite lacking inductive primitives, System F can *encode* arbitrary strictly-positive inductive types via Church / Böhm–Berarducci encodings. The recipe: an inductive type with constructors $c_1 : A_1 arrow.r ... arrow.r T$, ..., $c_n : B_1 arrow.r ... arrow.r T$ is encoded as
$ T = forall alpha . (A_1 arrow.r ... arrow.r alpha) arrow.r ... arrow.r (B_1 arrow.r ... arrow.r alpha) arrow.r alpha $

with recursive references to $T$ in argument types replaced by $alpha$. A value is its own *fold*.

*Theorem (Geuvers 2001).* The *full induction principle* — yielding *dependent* eliminators — is *not* derivable in System F from Church encodings. Only the *non-dependent* recursor is.

This is one of the main motivations for moving to dependent type theory: there one can both define and *reason about* inductive data.

=== Binary Trees in System F

$ "Tree" alpha &:= forall beta . (alpha arrow.r beta) arrow.r (beta arrow.r beta arrow.r beta) arrow.r beta \
"leaf" &:= Lambda alpha . lambda a : alpha . Lambda beta . lambda l : alpha arrow.r beta . lambda n : beta arrow.r beta arrow.r beta . l space a \
"node" &:= Lambda alpha . lambda L R : "Tree" alpha . Lambda beta . lambda l : alpha arrow.r beta . lambda n : beta arrow.r beta arrow.r beta . n space (L [beta] space l space n) space (R [beta] space l space n) $

Tree-fold is *built in*: applying a tree to $(l, n)$ folds it.

== Recursive Types via Newtype + Fix

System F does not directly include *recursive types* $mu alpha . tau$ (e.g., for streams or non-Church-encoded data). Languages add them separately:
- *Iso-recursive* types (ML-style): $mu alpha . tau$ is *different from* $[alpha |-> mu alpha . tau] tau$; explicit `roll`/`unroll` coercions.
- *Equi-recursive* types (some experimental systems): identified up to the obvious infinite unfolding.

Adding *iso-recursive* types to System F preserves SN as long as recursion is restricted to *positive* occurrences. Adding *unrestricted* recursion (negative occurrences, like $mu alpha . alpha arrow.r alpha$) yields untyped $lambda$ embeddability and destroys SN.

== Predicativity Stratification

A type theory's *proof-theoretic strength* is measured by the ordinal of its provably-recursive functions.

#table(
  columns: (auto, auto),
  [*System*], [*Ordinal strength*],
  [$lambda^arrow.r$], [$omega^omega$],
  [Gödel's System T], [$epsilon_0$],
  [HM / ML], [$omega^omega$ (same as STLC)],
  [System F], [$Gamma_0$ — Feferman–Schütte ordinal],
  [$F_omega$], [larger, complicated],
  [Predicative MLTT (1 universe)], [Bachmann–Howard],
  [MLTT + W-types + universes], [grows with universes],
  [CIC], [vastly larger — beyond accepted classical ordinals],
)

The take-away: System F is *enormously* stronger than HM despite a small syntactic addition — the ability to *abstract* over types and *re-apply*. The price is undecidable inference; the gain is provable totality for an enormous class of programs.

== Parametricity Limits

Parametricity holds in *pure* System F but breaks under common extensions:
- *Reference cells* (`ref`) — destroys parametricity since references expose representation.
- *Exceptions* (in some forms) — observing a thrown exception reveals control flow.
- *`seq`* in Haskell — observing whether a value is bottom breaks the "free" naturality.
- *`unsafeCoerce`* — patently breaks everything.
- *Typecase* / *Typeable* — runtime type inspection contradicts the assumption that the type is unknown to the function.
- *Non-termination* — even pure non-termination weakens parametricity to a *step-indexed* analogue.

This is one of the reasons functional programmers value purity: *pure* polymorphic types come with strong free theorems; *impure* ones do not.

== Polarity and Sum Types

In a categorical model, types split into *positive* (sums, products with $beta$) and *negative* (products with $eta$, exponentials). System F's $forall$ is *negative*; its existentials and inductives (when encoded) inherit positivity.

*Focusing* and *polarised* type systems (Andreoli 1992 for linear logic; Zeilberger 2008 for polarised intuitionistic logic) make this distinction explicit. The Church encoding $exists alpha . tau = forall beta . (forall alpha . tau arrow.r beta) arrow.r beta$ is exactly the *negative shift* of a positive existential: a CPS-style encoding.

== System F-omega and Type Constructors

The *kinding rules* of $F_omega$:

```text
  alpha : kappa in Delta
  ---------------------- (K-VAR)
  Delta |- alpha : kappa

  Delta, alpha : kappa_1 |- tau : kappa_2
  ------------------------------------------- (K-TLAM)
  Delta |- lam alpha : kappa_1. tau : kappa_1 -> kappa_2

  Delta |- tau : kappa_1 -> kappa_2    Delta |- sigma : kappa_1
  -------------------------------------------------------------- (K-TAPP)
  Delta |- tau sigma : kappa_2

  Delta |- tau_1 : *    Delta |- tau_2 : *
  ---------------------------------------- (K-ARROW)
  Delta |- tau_1 -> tau_2 : *

  Delta, alpha : kappa |- tau : *
  ------------------------------- (K-ALL)
  Delta |- forall alpha : kappa. tau : *
```

Note that *only* kind $*$ types appear in arrow / forall positions — proper types are inhabited; higher-kinded types are operators.

Worked example: $"State" : * arrow.r * arrow.r *$, defined as $"State" = lambda s : * . lambda a : * . s arrow.r s times a$. Then $"State" "Int" "Bool" = "Int" arrow.r "Int" times "Bool"$ by $beta$ at the type level.

== Existential Quantification in Logic

Under Curry–Howard, $exists alpha . P(alpha)$ corresponds to $exists$ at the propositional level (second-order). The Church encoding's *unpack* matches the elimination rule of $exists$:

If $exists alpha . P(alpha)$ and from any $alpha$ together with a proof of $P(alpha)$ one can derive $Q$, then $Q$ — provided $alpha$ does not appear in $Q$.

This is the *eigenvariable* condition in disguise, mirroring T-TABS.

== The $forall$/$exists$ Duality

A polymorphism deeply rooted in System F: every $exists$ encoding is a CPS-transform of a $forall$. Dually, $forall alpha . F alpha tilde.equiv$ ? — well, there's no clean dual; the asymmetry reflects the *intuitionistic* nature (no double-negation elimination).

But adding *delimited control* or *call/cc* — equivalently, allowing classical reasoning — yields a richer story. *Parigot's* $lambda mu$-calculus (1992) adds named continuations and *names* $alpha, beta, ...$ at a separate level; its types are the *classical* second-order propositional formulas. SN holds (Parigot 1997, David–Nour 2003).

== Conservativity Results

*Theorem (Reynolds 1984, Mitchell 1986).* System F is *conservative* over STLC: a term not mentioning $forall$ is typable in F <==> it is typable in STLC.

*Theorem.* HM is *conservative* over its predicative System F fragment.

*Non-conservativity:* adding *type families* or *GADTs* to Haskell adds equations that are not derivable from system FC alone — they require the equation axioms.

== Worked Example: A Polymorphic Stack

```ocaml
module type STACK = sig
  type 'a t
  val empty : 'a t
  val push  : 'a -> 'a t -> 'a t
  val pop   : 'a t -> ('a * 'a t) option
end

(* List-based implementation *)
module ListStack : STACK = struct
  type 'a t = 'a list
  let empty = []
  let push x s = x :: s
  let pop = function [] -> None | x :: s -> Some (x, s)
end
```

By parametricity, *no* client of `STACK` can distinguish `ListStack` from any other implementation respecting the spec. This is *representation independence* — the cornerstone of modular programming.

== Worked Example: Existential Counters

```ocaml
(* Existential ADT in OCaml first-cal(C) modules *)
module type COUNTER = sig
  type t
  val init : t
  val incr : t -> t
  val read : t -> int
end

let intC : (module COUNTER) =
  (module struct type t = int let init = 0 let incr n = n+1 let read n = n end)

let pairC : (module COUNTER) =
  (module struct type t = int * int
                 let init = (0, 0)
                 let incr (a, b) = (a+1, b+a)
                 let read (a, _) = a
   end)
```

Both `intC` and `pairC` have type `(module COUNTER)`. Any client function `f : (module COUNTER) -> int` cannot distinguish them by *behavioural observation* — by parametricity. This is *representation independence* in action.

== Historical Notes

Jean-Yves Girard discovered System F in 1971, presented in his thesis (1972) as *Système F*, in the context of proving the *Takeuti conjecture* — the cut-elimination theorem (and hence consistency) for second-order arithmetic. Girard's main technical contribution was the *reducibility candidates* method, generalising Tait's reducibility from STLC to handle impredicative quantification.

John Reynolds, working independently in the programming-languages tradition, arrived at the same calculus in 1974 as the type-theoretic foundation of *parametric polymorphism* in his paper "Towards a Theory of Type Structure". Reynolds' (1983) *abstraction theorem* — relational parametricity — provided the semantic justification for the slogan "polymorphic functions don't inspect their arguments".

Philip Wadler's 1989 paper "Theorems for Free!" popularised parametricity among programmers, deriving practical equations from polymorphic types alone.

The undecidability of $F_(<:)$ subtyping was a surprise: Pierce (1994) found the encoding of two-counter machines that finally proved the long-standing open question. The undecidability of System F type inference (Wells 1994; published 1999) closed another open problem with a beautiful reduction to semi-unification.

System $F_omega$ — adding type operators — was already present in Girard's thesis. The Barendregt cube was introduced by Barendregt (1991) as a unifying framework for the pure type systems (Berardi–Terlouw 1989).

The legacy of System F is everywhere in modern type theory: Haskell, Coq, Agda, Lean, Idris, F\* — all of them descend from System F. Parametricity remains an active research area; recent work on *internal parametricity* (Bernardy–Lasson 2011, Bernardy–Coquand–Moulin 2015) bakes Reynolds' theorem *into* the type theory itself, so free theorems become provable inside the system rather than only in its metatheory.
