= System F and Parametricity

System F — the *polymorphic $lambda$-calculus*, or second-order $lambda$-calculus — extends the simply-typed $lambda$-calculus with quantification over types. Discovered independently by Jean-Yves Girard (1971, thesis 1972) as a tool to prove the consistency of second-order Peano arithmetic, and rediscovered by John Reynolds (1974) as the type system underlying polymorphic programming, System F is the bridge between proof theory and modern functional language design.

*See also:* _Simply-Typed Lambda Calculus_, _Type Systems_, _Dependent Types_, _Categorical Semantics_

This chapter develops System F in full. We give the syntax, typing rules with T-TABS and T-TAPP, and worked Church encodings of $"Bool"$, $"Nat"$, $"Pair"$, and $"List"$ as polymorphic types. We show why the $Y$-combinator is not typable. We sketch Girard's strong-normalization proof via *reducibility candidates*, the genuine innovation over Tait's plain reducibility predicates. We develop Reynolds' *abstraction theorem* (parametricity) and Wadler's "theorems for free", deriving in detail the free theorems for the polymorphic identity, swap, and map types. We treat existential types and Mitchell–Plotkin abstract data types. We climb to System $F_omega$ and the Barendregt cube. We close with Wells' undecidability of System F type inference and Pierce's undecidability of full $F_(<:)$.

== Syntax

*Types.*
$ tau ::= alpha | tau_1 arrow.r tau_2 | forall alpha. tau $

where $alpha, beta, gamma, ...$ range over a countably infinite set of *type variables*. The quantifier $forall alpha. tau$ binds $alpha$ in $tau$. We work up to $alpha$-equivalence of bound type variables.

*Terms* (Church presentation).
$ e ::= x | lambda x : tau . e | e_1 space e_2 | Lambda alpha . e | e [tau] $

Two new term-formers: the *type abstraction* $Lambda alpha . e$ (binds the type variable $alpha$ in the body $e$) and *type application* $e[tau]$ (instantiates the type variable bound by $Lambda$ at $tau$). Greek capital $Lambda$ is used at the term level; lowercase $lambda$ remains for ordinary abstraction.

*Free type variables.* Defined by mutual recursion with free term variables. Notation $"FTV"(tau)$ and $"FTV"(e)$:
$ "FTV"(alpha) &= {alpha} \
"FTV"(tau_1 arrow.r tau_2) &= "FTV"(tau_1) union "FTV"(tau_2) \
"FTV"(forall alpha. tau) &= "FTV"(tau) \\ {alpha} $

A *kinding judgment* $Delta tack.r tau$ (where $Delta$ is a finite set of type variables) certifies that $"FTV"(tau) subset.eq Delta$. In $F_omega$ this becomes a richer judgment $Delta tack.r tau : kappa$ where $kappa$ is a *kind* (see below).

*Capture-avoiding type substitution.* $[alpha |-> sigma] tau$ behaves exactly like term substitution, $alpha$-renaming bound type variables as needed.

== Static Semantics

The typing judgment is $Delta; Gamma tack.r e : tau$, where $Delta$ tracks type variables in scope and $Gamma$ tracks term variables. We write $Delta; Gamma$ as $Gamma$ when $Delta$ is clear.

```text
  x : tau in Gamma
  --------------------                       (T-VAR)
  Delta; Gamma |- x : tau

  Delta |- tau_1   Delta; Gamma, x : tau_1 |- e : tau_2
  ------------------------------------------------------   (T-ABS)
  Delta; Gamma |- lam x : tau_1. e : tau_1 -> tau_2

  Delta; Gamma |- e_1 : tau_1 -> tau_2    Delta; Gamma |- e_2 : tau_1
  ------------------------------------------------------------------    (T-APP)
  Delta; Gamma |- e_1 e_2 : tau_2

  Delta, alpha; Gamma |- e : tau              (alpha not in Delta, FTV(Gamma))
  --------------------------------------                                  (T-TABS)
  Delta; Gamma |- Lam alpha. e : forall alpha. tau

  Delta; Gamma |- e : forall alpha. tau     Delta |- sigma
  ---------------------------------------------------------               (T-TAPP)
  Delta; Gamma |- e [sigma] : [alpha |-> sigma] tau
```

The side condition in T-TABS — that $alpha$ does not occur in $Gamma$ — is the analogue of the universal-introduction *eigenvariable* condition in natural deduction. Without it, one could derive $x : alpha tack.r Lambda alpha . x : forall alpha . alpha$, a contradiction in the Curry–Howard reading.

*Lemma (Type Substitution).* If $Delta, alpha; Gamma tack.r e : tau$ and $Delta tack.r sigma$, then $Delta; [alpha |-> sigma] Gamma tack.r [alpha |-> sigma] e : [alpha |-> sigma] tau$.

*Lemma (Inversion).* If $Delta; Gamma tack.r Lambda alpha . e : rho$, then $rho = forall alpha. tau$ with $Delta, alpha; Gamma tack.r e : tau$. If $Delta; Gamma tack.r e [sigma] : rho$, then $Delta; Gamma tack.r e : forall alpha. tau$ with $rho = [alpha |-> sigma] tau$ for some $tau$.

== Dynamic Semantics

Reduction is generated by two redex schemes:
$ (lambda x : tau . e_1) space e_2 &arrow.r_beta [x |-> e_2] e_1 space space space space space (beta) \
(Lambda alpha . e) [sigma] &arrow.r_beta [alpha |-> sigma] e space space space space space (beta_2) $

The second is *type-level $beta$* — instantiating a polymorphic value at a type. Both rules are subject to congruence (compatible closure).

*Theorem (Subject Reduction).* If $Delta; Gamma tack.r e : tau$ and $e arrow.r e'$, then $Delta; Gamma tack.r e' : tau$.

*Proof.* Induction on the reduction. The $beta_2$ case uses the Type Substitution Lemma. $square$

== Examples and Church Encodings

=== The Polymorphic Identity

$ "id" = Lambda alpha . lambda x : alpha . x : forall alpha . alpha arrow.r alpha $

Instantiation: $"id" ["Int"] : "Int" arrow.r "Int"$; $"id" [forall beta . beta arrow.r beta] : (forall beta . beta arrow.r beta) arrow.r (forall beta . beta arrow.r beta)$. The second is the famous *impredicative* instantiation — $"id"$ applied at its *own* type. This is the source of System F's expressive power and the source of its proof-theoretic strength: the second-order quantifier ranges over a universe that includes the type being defined.

=== Booleans

$ "Bool" &:= forall alpha . alpha arrow.r alpha arrow.r alpha \
"true"  &:= Lambda alpha . lambda x : alpha . lambda y : alpha . x \
"false" &:= Lambda alpha . lambda x : alpha . lambda y : alpha . y \
"if" b space "then" space e_1 "else" space e_2 &:= b [tau] space e_1 space e_2 $

where $tau$ is the common type of $e_1, e_2$. Verify: $"if" "true" "then" 3 "else" 5 = ("true"["Int"]) space 3 space 5 = 3$. The Boolean *eliminator* is just type instantiation followed by application.

=== Natural Numbers (Church Numerals)

$ "Nat" &:= forall alpha . (alpha arrow.r alpha) arrow.r alpha arrow.r alpha \
overline(0) &:= Lambda alpha . lambda f : alpha arrow.r alpha . lambda x : alpha . x \
overline(n+1) &:= Lambda alpha . lambda f : alpha arrow.r alpha . lambda x : alpha . f^(n+1) (x) \
"succ" &:= lambda n : "Nat" . Lambda alpha . lambda f : alpha arrow.r alpha . lambda x : alpha . f (n [alpha] space f space x) \
"add"  &:= lambda m n : "Nat" . Lambda alpha . lambda f : alpha arrow.r alpha . lambda x : alpha . m [alpha] space f space (n [alpha] space f space x) \
"mul"  &:= lambda m n : "Nat" . Lambda alpha . lambda f : alpha arrow.r alpha . m [alpha] space (n [alpha] space f) $

Iteration is *built in*: $n [tau] space s space z$ applies $s$ to $z$ exactly $n$ times.

*Theorem.* The functions $"Nat" arrow.r "Nat"$ representable in System F are exactly the *provably total recursive functions* of second-order Peano arithmetic — a strictly larger class than those provable in $"PA"$ (Girard 1972). This includes Ackermann's function and many beyond.

=== Pairs

$ "Pair" alpha beta &:= forall gamma . (alpha arrow.r beta arrow.r gamma) arrow.r gamma \
"pair" &:= Lambda alpha beta . lambda x : alpha . lambda y : beta . Lambda gamma . lambda k : alpha arrow.r beta arrow.r gamma . k space x space y \
"fst"  &:= Lambda alpha beta . lambda p : "Pair" alpha beta . p [alpha] (lambda x : alpha . lambda y : beta . x) \
"snd"  &:= Lambda alpha beta . lambda p : "Pair" alpha beta . p [beta] (lambda x : alpha . lambda y : beta . y) $

Verify $"fst" ["Int", "Bool"] ("pair" ["Int", "Bool"] space 3 space "true") arrow.r^* 3$.

=== Lists

$ "List" alpha &:= forall beta . (alpha arrow.r beta arrow.r beta) arrow.r beta arrow.r beta \
"nil"         &:= Lambda alpha . Lambda beta . lambda c : alpha arrow.r beta arrow.r beta . lambda n : beta . n \
"cons"        &:= Lambda alpha . lambda h : alpha . lambda t : "List" alpha . \
                  &space space Lambda beta . lambda c : alpha arrow.r beta arrow.r beta . lambda n : beta . c space h space (t [beta] space c space n) $

A list *is* its own fold: $"foldr" c space n space ell = ell [beta] space c space n$. The representation is naturally a *Böhm–Berarducci* encoding (Böhm–Berarducci 1985), and it generalises to all strictly-positive inductive types.

=== Existentials (Anticipating §)

Church-encoded $exists alpha . tau$ as $forall beta . (forall alpha . tau arrow.r beta) arrow.r beta$ — see the existentials section below.

== Strong Normalization (Girard 1972)

*Theorem (Girard 1972).* Every well-typed term of System F is strongly normalising.

This is *substantially* harder than the STLC case. The naïve attempt — define $cal(R)_tau$ by induction on $tau$, with $cal(R)_(forall alpha . tau) = inter.big_(sigma) [alpha |-> ?] cal(R)_(tau)$ — fails because the type $sigma$ may be larger than $forall alpha . tau$ itself (impredicativity!), so no structural induction on types is available. Tait's plain reducibility works for STLC but breaks here.

Girard's solution: *reducibility candidates*. The idea is to *give up* on defining $cal(R)$ directly and instead axiomatize a *family* of acceptable interpretations. A type variable $alpha$ is interpreted by *any* candidate satisfying the closure conditions; $forall alpha . tau$ then quantifies semantically over all candidates.

=== Reducibility Candidates

A set $cal(C)$ of closed terms of a given type is a *candidate* (write $cal(C) in "CR"_tau$) iff:
- *(CR1)* Every $e in cal(C)$ is strongly normalising.
- *(CR2)* If $e in cal(C)$ and $e arrow.r e'$, then $e' in cal(C)$.
- *(CR3)* If $e$ is *neutral* (not a $lambda$- or $Lambda$-abstraction) and every $e'$ with $e arrow.r e'$ lies in $cal(C)$, then $e in cal(C)$.

*Note.* CR3 implies that every candidate contains all *strongly-neutral normal forms* (variables, applications to normal forms with neutral head). In particular candidates are nonempty.

*Notational difference from STLC.* In Girard's framework, the *interpretation* $[| tau |]_eta in "CR"$ is parameterised by an *environment* $eta$ assigning to each free type variable a candidate. Define it by recursion on $tau$:
$ [| alpha |]_eta &= eta(alpha) \
[| tau_1 arrow.r tau_2 |]_eta &= {e : forall e' in [| tau_1 |]_eta . space e space e' in [| tau_2 |]_eta} \
[| forall alpha . tau |]_eta &= inter.big_(cal(C) in "CR") space [| tau |]_(eta, alpha |-> cal(C)) $

The big intersection is the crux. Because we range over the *abstract* class of candidates rather than concrete types, the recursion is on $tau$ rather than on the (semantic) type of the interpretation.

*Lemma.* For every type $tau$ and environment $eta$, $[| tau |]_eta in "CR"$.

*Proof.* Induction on $tau$. Variables: by assumption $eta(alpha) in "CR"$. Arrow: verify CR1, CR2, CR3 directly; CR3 uses that $e space e'$ is neutral when $e$ is, plus IH. Universal: an intersection of candidates is a candidate (intersect the closure conditions pointwise). $square$

*Substitution Lemma.* $[| [alpha |-> sigma] tau |]_eta = [| tau |]_(eta, alpha |-> [| sigma |]_eta)$.

*Main Theorem.* If $Delta; Gamma tack.r e : tau$, then for every type-environment $eta$ assigning candidates to $Delta$, and every closing substitution $gamma$ with $gamma(x) in [| Gamma(x) |]_eta$ for each $x$, we have $gamma(e) in [| tau |]_eta$.

*Proof.* Induction on the typing derivation.
- T-VAR: by assumption.
- T-APP: by definition of arrow candidate.
- T-ABS: analogue of the STLC Abstraction Lemma, using CR3 to handle the redex case; $beta$-step reaches the IH.
- T-TAPP: by Substitution Lemma, $gamma(e)[sigma] in [| forall alpha . tau' |]_eta subset.eq [| tau' |]_(eta, alpha |-> [| sigma |]_eta) = [| [alpha |-> sigma] tau' |]_eta$, modulo the fact that type application is itself neutral and reduces via $beta_2$ — handled by CR3.
- T-TABS: for every candidate $cal(C)$ and the extended environment, show $gamma(e) in [| tau |]_(eta, alpha |-> cal(C))$ by IH; conclude $Lambda alpha . gamma(e) in [| forall alpha . tau |]_eta$. The reduction $(Lambda alpha . gamma(e)) [sigma] arrow.r [alpha |-> sigma] gamma(e)$ is the $beta_2$-redex, handled by an analogue of the Abstraction Lemma. $square$

*Corollary.* Take $eta(alpha) = "SN"_alpha$ and $gamma(x_i) = x_i$ (variables are in every candidate by CR3). Then $e in [| tau |]_eta$, hence $e$ is SN by CR1. $square$

=== Why Plain Reducibility Fails

In STLC, $cal(R)_tau$ was defined by induction on $tau$. In System F we cannot do the same for $forall alpha . tau$: defining it as $inter_sigma cal(R)_([alpha |-> sigma] tau)$ would require already having $cal(R)$ at *every* type $sigma$ — including types *larger* than $forall alpha . tau$. The recursion is non-well-founded. Girard's solution decouples the *type* from its *interpretation*: candidates are an axiomatic class, not constructed by induction on syntax. The price is a slightly more elaborate proof; the prize is SN for all of System F.

== The $Y$-Combinator is Not Typable

The untyped fixed-point combinator
$ Y = lambda f . (lambda x . f (x space x)) (lambda x . f (x space x)) $
satisfies $Y space f arrow.r^* f (Y space f)$ and produces non-terminating reductions. If $Y$ were typable in System F at the polymorphic type $tau = forall alpha . (alpha arrow.r alpha) arrow.r alpha$, then for any type $alpha$ and any $f : alpha arrow.r alpha$, the term $Y space [alpha] space f$ would be a closed well-typed term of type $alpha$. By Strong Normalization, $Y space f$ is SN. But $Y space f$ reduces to $f (Y space f)$ which reduces to $f (f (Y space f))$ etc., infinite reduction — contradiction. Hence no fixed-point combinator is typable in System F. Adding $"fix"$ as a primitive (with its own typing rule $forall alpha . (alpha arrow.r alpha) arrow.r alpha$ and reduction rule) makes the system Turing-complete but destroys SN and logical consistency.

== Reynolds' Parametricity

*The intuition.* A function of type $forall alpha . alpha arrow.r alpha$ knows nothing about $alpha$; the only thing it can do with its argument is return it. Hence the only inhabitant is (up to $beta eta$) the identity. Reynolds (1983) formalised this slogan via a relational interpretation, generalising the candidate construction.

=== The Relational Interpretation

For each type $tau$ and each *relation environment* $rho$ assigning to each type variable $alpha$ a relation $rho(alpha) : A_alpha <-> B_alpha$ between two sets, define a binary relation $[| tau |]_rho : [| tau |]_(rho_1) <-> [| tau |]_(rho_2)$:

$ [| alpha |]_rho &= rho(alpha) \
[| tau_1 arrow.r tau_2 |]_rho &= {(f, g) : forall (a, b) in [| tau_1 |]_rho . space (f space a, g space b) in [| tau_2 |]_rho} \
[| forall alpha . tau |]_rho &= {(p, q) : forall A B . forall R : A <-> B . space (p[A], q[B]) in [| tau |]_(rho, alpha |-> R)} $

The first projection $rho_1(alpha) = A_alpha$, second $rho_2(alpha) = B_alpha$; for $tau_1 arrow.r tau_2$, $[| tau_1 arrow.r tau_2 |]_(rho_1) = [| tau_1 |]_(rho_1) arrow.r [| tau_2 |]_(rho_1)$.

*Theorem (Reynolds 1983, Abstraction).* For every closed term $emptyset tack.r e : tau$ and every relation environment $rho$, the pair $([| e |]_(rho_1), [| e |]_(rho_2)) in [| tau |]_rho$. In particular if $e$ is closed and $rho$ has all $rho(alpha) = $ identity, the theorem says $e$ is related to itself — *every term respects every parametric relation*.

*Proof.* Induction on the typing derivation, exactly mirroring the SN proof but with binary relations in place of candidates. $square$

== Theorems for Free (Wadler 1989)

Reynolds' abstraction theorem yields immediate free theorems derivable from the type alone, without inspecting the implementation.

=== Free Theorem for $forall alpha . alpha arrow.r alpha$

Take a closed $i : forall alpha . alpha arrow.r alpha$. By parametricity with relation $R = {(a, a') : a' = h(a)}$ — the graph of an arbitrary function $h : A arrow.r B$ — we get $(i[A], i[B]) in [| alpha arrow.r alpha |]_(alpha |-> R)$, i.e., for every $a : A$, $(i[A] space a, i[B] space (h space a)) in R$, i.e., $i[B] (h space a) = h (i[A] space a)$. So $i$ is *natural* in $alpha$.

Specialising $A = B = "Unit"$, $h = "id"$: $i["Unit"] : "Unit" arrow.r "Unit"$ takes $()$ to $()$. Then by the naturality square instantiated at $A = "Unit"$, $h(()) = a$ for arbitrary $a : B$: $i[B] space a = h (i["Unit"] ()) = h(()) = a$. Hence $i[B] = "id"_B$ for every $B$, so $i = Lambda alpha . lambda x . x$ extensionally.

*Conclusion.* Up to $beta eta$, the *only* inhabitant of $forall alpha . alpha arrow.r alpha$ is the identity.

=== Free Theorem for $forall alpha . "List" alpha arrow.r "List" alpha$

Take $r : forall alpha . "List" alpha arrow.r "List" alpha$. Specialising the abstraction theorem at the graph of $h : A arrow.r B$, we get for every list $"xs" : "List" A$:
$ r[B] ("map" h space "xs") = "map" h space (r[A] space "xs") $

So $r$ *commutes with $"map"$*. This holds for *every* function $r$ of that type: $"reverse"$, $"tail"$ (when defined), $"filter" p$ (no — $p$ depends on $alpha$), but uniform list-permutations and prefix-droppers.

=== Free Theorem for $forall alpha . alpha times alpha arrow.r alpha$

Take $f : forall alpha . alpha times alpha arrow.r alpha$. Parametricity, instantiated at the *graph* of an arbitrary function $h : A arrow.r B$ (a genuine relation), yields the naturality law $f[B] (h space a_1, h space a_2) = h (f[A] (a_1, a_2))$ for all $a_1, a_2 : A$. That is, $f$ commutes with every $h$ on both components.

Now pick $A = "Bool"$, $a_1 = "true"$, $a_2 = "false"$, $B = "Bool"$, $h = "id"$: $f["Bool"] ("true", "false") in {"true", "false"}$. By a case analysis using $h = $ constant function, we can show $f$ is *either* uniformly $pi_1$ *or* uniformly $pi_2$. (Detailed argument: define $h_1 (x) = "true"$ when $x = a_1$ else "false"; the naturality square forces a binary choice.)

*Conclusion.* The only inhabitants of $forall alpha . alpha times alpha arrow.r alpha$ are $pi_1$ and $pi_2$.

=== Free Theorem for $forall alpha beta . (alpha arrow.r beta) arrow.r "List" alpha arrow.r "List" beta$

Take such a $m$. The free theorem says: for every $f : A_1 arrow.r B_1$, $g : A_2 arrow.r B_2$, $h_alpha : A_1 arrow.r A_2$, $h_beta : B_1 arrow.r B_2$ with $h_beta circle.small f = g circle.small h_alpha$, we have $"map" h_beta circle.small m[A_1, B_1] f = m[A_2, B_2] g circle.small "map" h_alpha$. Setting $h_alpha = "id"$, $g = h_beta circle.small f$ yields $"map" (h_beta circle.small f) space "xs" = "map" h_beta (m[A_1, B_1] f space "xs")$, i.e., $m$ is *functorial* (preserves identity is similar). Wadler's slogan: *every polymorphic list-mapping function is up to $beta eta$ equal to $"map" f$ followed by some permutation/dropping that is independent of $f$* — but for the type $forall alpha beta . (alpha arrow.r beta) arrow.r "List" alpha arrow.r "List" beta$ specifically, by also requiring the relational input $f$ to vary, we get that $m = "map"$ (up to $beta eta$).

=== Implications

Parametricity is not merely a curiosity: it underlies *representation independence* (abstract types are not exposed by polymorphic clients), *foldr-build fusion* (Gill–Launchbury–Peyton Jones 1993), and the *Yoneda lemma* in functor land. It also fails dramatically when the language has *non-parametric* features: `typecase`, runtime type representations, `seq` (which observes evaluation), and reference cells all break parametricity.

== Existential Types and Abstract Data Types

Mitchell–Plotkin (1988) recognised that *existential types* model abstract data types. The Church-encoding:
$ exists alpha . tau &:= forall beta . (forall alpha . tau arrow.r beta) arrow.r beta \
"pack" tau "with" e "as" exists alpha . tau' &:= Lambda beta . lambda k : forall alpha . tau' arrow.r beta . k [tau] space e \
"unpack" angle.l alpha, x angle.r = e "in" e' &:= e [tau_("answer")] (Lambda alpha . lambda x : tau' . e') $

The introduction $"pack"$ packages a *concrete* witness $tau$ together with a value $e : [alpha |-> tau] tau'$, hiding the witness behind the existential. The elimination $"unpack"$ binds a *fresh* type variable $alpha$ (the abstract type) and a term variable $x$ of representation type $tau'$. Crucially, the eliminator's body $e'$ may not mention $alpha$ in its result type — this is *information hiding*.

*Example.* A counter ADT:
$ "Counter" &:= exists alpha . alpha times (alpha arrow.r alpha) times (alpha arrow.r "Int") \
"intCounter" &:= "pack" "Int" "with" (0, lambda x . x + 1, lambda x . x) "as" "Counter" $

Clients see only $alpha$, never `Int`. They can $"init"$, $"incr"$, and $"read"$, but not — by parametricity! — exploit the representation.

*Parametricity gives ADT abstraction.* Two implementations of $"Counter"$ are observationally equivalent <==> related by a *simulation* $R$ (a relation between the two representation types respecting init/incr/read). This is the formal content of *representation independence* (Reynolds 1983; Mitchell 1986).

== System $F_omega$: Higher Kinds

System $F_omega$ adds *type-level functions*. The grammar becomes layered:

*Kinds.* $kappa ::= * | kappa_1 arrow.r kappa_2$.

*Type constructors.* $tau ::= alpha | tau_1 arrow.r tau_2 | forall alpha : kappa . tau | lambda alpha : kappa . tau | tau_1 space tau_2$.

The two new type-formers $lambda alpha : kappa . tau$ and $tau_1 space tau_2$ allow type-level abstraction and application. A *type-level* $beta$-conversion is added:
$ (lambda alpha : kappa . tau) space sigma arrow.r_beta [alpha |-> sigma] tau $

A *kind judgment* $Delta tack.r tau : kappa$ ensures well-formedness:

```text
  alpha : kappa in Delta                       Delta |- tau_1 : *    Delta |- tau_2 : *
  ---------------------- (K-VAR)               ---------------------------------------- (K-ARROW)
  Delta |- alpha : kappa                       Delta |- tau_1 -> tau_2 : *

  Delta, alpha : kappa |- tau : *              Delta, alpha : kappa_1 |- tau : kappa_2
  --------------------------------- (K-ALL)    ------------------------------------------- (K-TLAM)
  Delta |- forall alpha : kappa. tau : *       Delta |- lam alpha : kappa_1. tau : kappa_1 -> kappa_2

  Delta |- tau_1 : kappa_1 -> kappa_2    Delta |- tau_2 : kappa_1
  ---------------------------------------------------------------- (K-TAPP)
  Delta |- tau_1 tau_2 : kappa
```

Types of kind $*$ are *proper* types (inhabited by terms). Types of higher kinds are *type operators* — type-level functions.

*Examples.*
- $"List" : * arrow.r *$ — a type operator taking a type to a type.
- $"State" : * arrow.r * arrow.r *$ — state transformer.
- $"Functor" : (* arrow.r *) arrow.r *$? — well, in Haskell `Functor` is a type *class*, but the underlying constructor maps a functor (kind $* arrow.r *$) to a constraint (kind `Constraint`).

The type equality used in T-APP, T-TAPP is now equality *modulo type-level $beta eta$* — this is decidable (type-level reduction is SN by the same candidate argument lifted one level), but the type checker must perform conversion.

*Theorem (Girard 1972).* $F_omega$ is strongly normalising at both the term and type levels.

== The Barendregt Cube

Barendregt (1991) organised the family of pure type systems into a *cube* indexed by three binary axes — the four kinds of dependency allowed:

#table(
  columns: (auto, auto, auto, auto),
  [*System*], [*Polymorphism (terms on types)*], [*Type operators (types on types)*], [*Dependent types (types on terms)*],
  [$lambda^arrow.r$ (STLC)], [no], [no], [no],
  [$lambda 2$ = System F], [*yes*], [no], [no],
  [$lambda omega$ = STLC + type ops], [no], [*yes*], [no],
  [$lambda omega 2$ = $F_omega$], [*yes*], [*yes*], [no],
  [$lambda P$ = LF], [no], [no], [*yes*],
  [$lambda P 2$], [*yes*], [no], [*yes*],
  [$lambda P omega$], [no], [*yes*], [*yes*],
  [$lambda C$ = CoC], [*yes*], [*yes*], [*yes*],
)

Terms depending on terms (ordinary $lambda$) is always present. The three axes correspond to three of the four corners of the *Pure Type System* (PTS) classification. The apex $lambda C$ — the *Calculus of Constructions* (Coquand–Huet 1988) — is the foundation of Coq (see _Dependent Types_).

*Geometric picture.* Visualise as a cube with $lambda^arrow.r$ at the origin and $lambda C$ at the diagonally opposite corner; each axis is one dependency. F sits adjacent to STLC by one edge; $F_omega$ two edges; CoC three.

== Decidability and Type Inference

=== Hindley–Milner Decidability

The *let-polymorphic* restriction of System F (no first-class $forall$ in argument positions; quantifiers only at $"let"$-bindings) — *Hindley–Milner* (HM; Damas–Milner 1982) — has decidable type inference in near-linear time (see _Type Systems_). This is the type system of ML, OCaml, Haskell 98.

=== System F Type Inference is Undecidable

*Theorem (Wells 1994).* Type inference for full (Curry-style) System F is undecidable. Type *checking* with annotations on all $Lambda$ and $[tau]$ is decidable (just walk the tree); but inferring a type for an unannotated term is undecidable.

*Proof sketch.* Wells gave a reduction from *semi-unification* — given a system of equations $tau_i = tau'_i$ and inequations $tau_j lt.eq.eq tau'_j$ (where $lt.eq.eq$ is "is a substitution instance of"), decide solvability. Semi-unification is undecidable (Kfoury–Tiuryn–Urzyczyn 1990). Wells encoded an arbitrary semi-unification problem as a System F typability problem: each inequation becomes a quantifier instantiation. $square$

=== System $F_omega$ Type Checking is Decidable but Expensive

Type checking $F_omega$ is *decidable* — type equality requires deciding $beta eta$-equality of type expressions, which is decidable because type-level reduction is SN (Girard 1972). But the checking *cost* can be huge:

*Theorem (Henglein–Mairson 1991, Statman 1979).* Deciding $beta$-equality in $F_omega$ is *not* elementary recursive: the worst-case time is a tower of exponentials whose height depends on the term.

Practical type checkers (Haskell's GHC, OCaml) restrict to fragments where this blow-up does not arise; full $F_omega$ as a *type system* is rarely directly exposed.

== Bounded Quantification: $F_(<:)$

Cardelli and Wegner (1985) extended System F with *subtyping* by adding a bound to each quantifier:
$ tau ::= ... | forall alpha <: sigma . tau | "Top" $

The bounded universal $forall alpha <: sigma . tau$ ranges only over subtypes of $sigma$. Typing rules include T-TAPP requiring $sigma' <: sigma$ for instantiation. Subtyping $tau_1 <: tau_2$ is defined by the usual contravariance of arrows, etc.

Two variants:
- *Kernel $F_(<:)$* (Curien–Ghelli 1992): subtyping of $forall alpha <: sigma . tau$ requires *equal* bounds. Decidable.
- *Full $F_(<:)$*: subtyping of $forall alpha <: sigma_1 . tau_1 <: forall alpha <: sigma_2 . tau_2$ requires $sigma_2 <: sigma_1$ (contravariance in the bound). This is the natural reading; this is what programmers want.

*Theorem (Pierce 1994).* Subtype-checking in full $F_(<:)$ is *undecidable*.

*Proof sketch.* Pierce reduced the halting problem for *two-counter Minsky machines* to $F_(<:)$ subtype-checking. The trick: encode the configuration $(q, c_1, c_2)$ of a counter machine as a type; the subtyping query $tau_q <: tau_(q')$ holds <==> the machine, starting from $q$, eventually reaches a state included in $q'$. Counter increment is encoded by wrapping in a $forall$; counter decrement uses the contravariance of bounds. Each subtyping step in the recursion mimics one machine step. Termination of subtype-checking would decide halting — impossible.

Hence Pierce's recommendation: stick to *kernel* $F_(<:)$ or impose a syntactic restriction. The languages Java and C\# face similar issues with bounded generics: Java's wildcard subtyping is, technically, undecidable as well (Grigore 2017 showed Java generic subtype-checking is Turing-complete).

== Implementation Notes

```haskell
-- A toy System F type checker in Haskell
data Ty
  = TVar Int                 -- de Bruijn type variable
  | TArr Ty Ty
  | TAll Ty                  -- binder: TAll body
  deriving (Eq, Show)

data Tm
  = Var Int
  | Lam Ty Tm
  | App Tm Tm
  | TLam Tm                  -- big-lambda
  | TApp Tm Ty               -- type application
  deriving (Show)

-- Type-level shift: shift bound type vars by d when crossing k binders
shiftTy :: Int -> Int -> Ty -> Ty
shiftTy d k (TVar i)    | i >= k = TVar (i + d)
                        | otherwise = TVar i
shiftTy d k (TArr a b)  = TArr (shiftTy d k a) (shiftTy d k b)
shiftTy d k (TAll t)    = TAll (shiftTy d (k+1) t)

-- Substitute the topmost type variable with s
substTy :: Ty -> Ty -> Ty
substTy s = go 0
  where
    go k (TVar i)
      | i == k    = shiftTy k 0 s
      | i >  k    = TVar (i - 1)
      | otherwise = TVar i
    go k (TArr a b) = TArr (go k a) (go k b)
    go k (TAll t)   = TAll (go (k+1) t)

infer :: [Ty] -> Tm -> Either String Ty
infer ctx (Var i)
  | i < length ctx = Right (ctx !! i)
  | otherwise      = Left "unbound"
infer ctx (Lam ty body) = do
  bt <- infer (ty : ctx) body
  return (TArr ty bt)
infer ctx (App f a) = do
  ft <- infer ctx f
  at <- infer ctx a
  case ft of
    TArr d c | d == at -> Right c
    TArr d _           -> Left ("expected " ++ show d ++ ", got " ++ show at)
    _                  -> Left "not a function"
infer ctx (TLam body) = do
  -- Shift term-variable types' type-vars under the new binder
  bt <- infer (map (shiftTy 1 0) ctx) body
  return (TAll bt)
infer ctx (TApp e ty) = do
  et <- infer ctx e
  case et of
    TAll body -> Right (substTy ty body)
    _         -> Left "type application of non-forall"
```

A real-world System F implementation (e.g., GHC Core's `System FC`) extends with coercions (for type-equality witnesses) and data constructors, but the above is the essential skeleton.

== The Logical Reading

Under Curry–Howard, System F corresponds to *second-order intuitionistic propositional logic* — propositional logic with quantification over *propositions*. The slogan:

$ "Types in F" &<-> "Formulas in IPC"^2 \
"Terms in F" &<-> "Proofs in IPC"^2 \
"Strong normalization" &<-> "Cut elimination for IPC"^2 $

The fact that System F is SN is exactly the *Hauptsatz* (cut-elimination theorem) for second-order intuitionistic logic. Girard's original motivation (his thesis) was precisely this — to give a constructive consistency proof of second-order Peano arithmetic by encoding it in $F$ and proving SN.

*Conservativity over $"PA"_2$.* The functions $"Nat" arrow.r "Nat"$ representable in System F are exactly the *provably total* recursive functions of second-order arithmetic ($"PA"_2$). This is a *vast* class: it goes well beyond the primitive-recursive functions, the multiply-recursive functions, the $epsilon_0$-recursive functions of Gödel's System T. It includes any function provably total in *any* finite extension of PA by induction over predicates definable in second-order logic. Practical implication: *any* function you can reasonably want to compute is expressible in System F — but you can't always type-infer the encoding.

