= Timed and Hybrid Automata

Classical finite automata are blind to time: they observe the order of events but not the intervals between them. Real systems -- communication protocols with retransmission timers, controllers governed by sample-and-hold loops, embedded software interacting with continuous physics -- have correctness properties that depend on quantitative timing. A railway interlocking that lowers the barrier in $30 s$ is correct; one that lowers it in $30$ minutes is not. The framework of *timed automata* (Alur--Dill 1994) extends finite automata with real-valued clocks and clock constraints, retaining decidable reachability while modelling dense time directly. *Hybrid automata* (Alur--Courcoubetis--Henzinger--Ho 1992; Henzinger 1996) generalize further to continuous variables governed by differential equations, exchanging decidability for expressiveness.

*See also:* _Omega-Automata_, _Weighted and Probabilistic Automata_, _Turing Machines and Computability_, _Program Semantics_

== Motivation: From Untimed to Timed Behaviour

A safety property such as "no two trains occupy the same block is a property of state. A property such as "every request is acknowledged within $200 "ms"$ is a property of state *and* elapsed time. Untimed automata can encode the second property only by discretizing time -- choosing a granularity $epsilon$ and modelling each tick as a transition -- which inflates the state space by a factor proportional to $1 slash epsilon$ and which is fundamentally an approximation. Timed automata model time as the continuum $RR_(>=0)$ directly. The miracle of Alur--Dill is that, despite the uncountable configuration space $L times RR^X_(>=0)$, the reachability relation is computable by quotienting under a finite equivalence -- the *region equivalence*.

== Timed Automata

=== Syntax

Fix a finite set $X$ of *clocks*, ranging over non-negative reals. The set $Phi(X)$ of *clock constraints* over $X$ is generated by the grammar

$ phi ::= x "≺"c | x - y "≺"c | phi_1 and phi_2 | "true" $

where $x, y in X$, $c in NN$, and $"≺" in {<, lt.eq, =, gt.eq, >}$. The diagonal constraints $x - y "≺"c$ extend the original definition of Alur--Dill, who allowed only the conjunctive (rectangular) fragment $x "≺"c$; diagonal constraints add no expressive power for closed automata but matter for the size of the region partition.

*Definition (Timed Automaton, Alur--Dill 1994).* A timed automaton is a tuple
$ cal(A) = (L, L_0, Sigma, X, E, "Inv") $
where

- $L$ is a finite set of *locations*,
- $L_0 subset.eq L$ is the set of *initial locations*,
- $Sigma$ is a finite alphabet of *actions*,
- $X$ is a finite set of *clocks*,
- $E subset.eq L times Phi(X) times Sigma times 2^X times L$ is a finite set of *edges*; an edge $(l, g, a, r, l')$ has *guard* $g in Phi(X)$, action $a in Sigma$, *reset set* $r subset.eq X$, and target $l'$,
- $"Inv" : L arrow.r Phi(X)$ assigns to each location an *invariant* constraining the clocks while control resides there.

=== Operational Semantics

A *clock valuation* is a map $v : X arrow.r RR_(>=0)$. We write $v + d$ for the valuation $x |-> v(x) + d$, and $v[r := 0]$ for the valuation that resets clocks in $r$ to zero and leaves others unchanged. The *configurations* of $cal(A)$ are pairs $(l, v) in L times RR^X_(>=0)$ such that $v models "Inv"(l)$.

There are two transition rules:

```text
  (delay)   d in RR_(>=0)     v + d' |= Inv(l)  for all  0 <= d' <= d
            ---------------------------------------------------------
                              (l, v)  --d-->  (l, v + d)

  (action)  e = (l, g, a, r, l') in E    v |= g    v[r:=0] |= Inv(l')
            ---------------------------------------------------------
                              (l, v)  --a-->  (l', v[r:=0])
```

A *run* is an alternating sequence of delays and actions starting from some $(l_0, v_0)$ with $l_0 in L_0$ and $v_0 = bb(0)$. The *timed language* $L(cal(A))$ consists of all *timed words* $(a_1, t_1)(a_2, t_2) dots$ with $t_1 lt.eq t_2 lt.eq dots$ produced by accepting runs (acceptance is by Büchi, Muller, or reachability condition, depending on context).

=== Worked Example: Light Switch with Timeout

```text
  Loc OFF, Inv: true                         Loc ON, Inv: x <= 30
        | press   guard: true                      | press   guard: x >= 1
        |   reset {x}                              |   reset {x}
        v                                          v
       ON, x := 0          <-----------------     OFF (back to OFF)
                            ("or")
        x = 30 / timeout    -----> OFF
```

The clock $x$ measures time since switching on. The invariant $x lt.eq 30$ in location ON forces a transition before $30$ time units; the guard $x = 30$ on the timeout edge fires exactly at the boundary; the guard $x gt.eq 1$ on the manual `press` edge models a $1$-second debounce.

== Region Equivalence

The state space $L times RR^X_(>=0)$ is uncountable, but only finitely many *qualitative* configurations are distinguishable by clock constraints with constants bounded by a maximum $c_x$ per clock.

*Definition (Region Equivalence, Alur--Dill 1994).* Let $c_x$ be the largest constant compared with clock $x$ in any guard or invariant of $cal(A)$. Two valuations $v, v'$ are *region-equivalent*, written $v tilde v'$, iff for every $x, y in X$:

1. $floor(v(x)) = floor(v'(x))$ whenever $v(x) lt.eq c_x$, and $v(x) > c_x <==> v'(x) > c_x$;
2. ${v(x)} = 0 <==> {v'(x)} = 0$ (where ${dot.op}$ denotes fractional part), whenever $v(x) lt.eq c_x$;
3. for $v(x), v(y) lt.eq c_x, c_y$: ${v(x)} lt.eq {v(y)} <==> {v'(x)} lt.eq {v'(y)}$.

Equivalence classes are called *regions*. A region is determined by (i) an integer part for each clock, capped at $c_x + 1$ (above maximum); (ii) a total preorder on the fractional parts of unsaturated clocks; (iii) which clocks have integer value.

*Theorem (Alur--Dill 1994).* Region equivalence is a *time-abstract bisimulation*: if $v tilde v'$ and $(l, v) arrow.r (l', v'')$ via an action $a$, there exists $v'''$ with $(l, v') arrow.r (l', v''')$ via $a$ and $v'' tilde v'''$; and similarly for the existence of a time-successor in a given region.

*Corollary (Region Automaton).* The quotient
$ cal(R)(cal(A)) = (L times "Regions"(X) slash tilde, dots.h) $
is a *finite* automaton that accepts the *untimed* projection of $L(cal(A))$. Its size is bounded by
$ |L| dot |X|! dot 2^(|X|) dot product_(x in X) (2 c_x + 2). $

The factor $|X|!$ counts the orderings of fractional parts; the $2^|X|$ counts which clocks are at integer values; the product counts the integer parts (with the saturation cap doubled to account for at integer vs. in open interval).

=== Reachability is Decidable, and Tight

*Theorem (Alur--Dill 1994).* The reachability problem for timed automata -- given $cal(A)$, location $l$, decide whether some run reaches a configuration with control at $l$ -- is *PSPACE-complete*.

*Proof sketch.* Membership: guess a path in $cal(R)(cal(A))$ on the fly; each region is representable in $O(|X| log c_max)$ bits, so the procedure runs in NPSPACE = PSPACE by Savitch. Hardness: reduce from acceptance of a linearly-bounded Turing machine; the encoding uses $O(n)$ clocks for tape contents (Alur--Dill).

*Theorem (Courcoubetis--Yannakakis 1992).* Reachability is PSPACE-hard already with *three* clocks. With one clock, it drops to NLOGSPACE; with two, it is NP-hard but PSPACE-membership is open in restricted fragments.

== Zones and Difference Bound Matrices

The region construction is intellectually clean but practically catastrophic: even modest automata produce trillions of regions. Tools instead use *zones* -- convex unions of regions described by conjunctions of difference constraints.

*Definition (Zone).* A *zone* over $X$ is a set $Z subset.eq RR^X_(>=0)$ of the form
$ Z = { v | and.big_(i,j) v(x_i) - v(x_j) prec_(i j) c_(i j) } $
where $x_0$ denotes a *fictitious zero clock*, $prec_(i j) in {<, lt.eq}$, and $c_(i j) in ZZ union {oo}$.

=== Difference Bound Matrices

A zone is represented by a *DBM* $D$ of size $(|X| + 1) times (|X| + 1)$ with entries $D_(i j) = (c_(i j), prec_(i j))$. The ordered semiring $({-oo} union ZZ times {<, lt.eq} union {oo}, min, +)$ uses lexicographic comparison of $(c, "≺")$ with $< "≺"lt.eq$.

*Canonical form.* A DBM is *canonical* if it is closed under entailment: $D_(i k) lt.eq D_(i j) + D_(j k)$ for all $i, j, k$. Canonicalization is the *all-pairs shortest path* problem: run Floyd--Warshall in $O(n^3)$ on the indices $0, dots, |X|$.

*Emptiness.* A canonical DBM represents the empty zone iff some diagonal entry $D_(i i)$ is strictly less than $(0, lt.eq)$.

=== Zone Operations

Let $Z$ be a canonical zone over $X$.

- *Future* (passage of time): $arrow.r.long Z = { v + d | v in Z, d gt.eq 0 }$. Implementation: set $D_(i 0) := oo$ for $i > 0$.
- *Reset* of clocks in $r$: $Z[r := 0] = { v[r := 0] | v in Z }$. For $x in r$, set $D_(x 0) = D_(0 x) = (0, lt.eq)$ and $D_(x y) = D_(0 y), D_(y x) = D_(y 0)$.
- *Intersection* with constraint $phi$: add the corresponding bounds and re-canonicalize.
- *Inclusion test* $Z subset.eq Z'$ on canonical DBMs: entrywise $D_(i j) lt.eq D'_(i j)$.

=== $cal(C)$-Closure (k-Normalization)

Naive forward exploration with zones may not terminate: clocks can grow unboundedly. *$cal(C)$-closure* (Daws--Tripakis 1998) abstracts a zone by truncating any entry referring to a constant larger than $c_max$. Formally, replace $D_(i j) = (c, "≺")$ by $(oo, <)$ if $c > c_max$, by $(-c_max, <)$ if $c < -c_max$, and re-canonicalize.

*Theorem (Daws--Tripakis 1998).* The $cal(C)$-closure abstraction is sound for reachability: a state is reachable iff some normalized zone containing it is reachable in the abstract semantics. The abstract state space is finite.

*Warning.* Naive $k$-normalization is *unsound* in the presence of *diagonal* constraints (Bouyer 2003). Sound abstractions for diagonal-free automata include the $"LU"$-abstraction (Behrmann--Bouyer--Larsen--Pelánek 2006), which uses per-clock lower and upper bounds rather than a single maximum.

== Determinization and Closure Properties

*Theorem (Alur--Dill 1994).* Timed automata are *not closed under complementation*: there exist timed languages $L(cal(A))$ whose complements are not timed-regular. They are closed under union and intersection (product construction with clock disjoint copies).

*Theorem (Alur--Dill 1994).* *Language inclusion* $L(cal(A)_1) subset.eq L(cal(A)_2)$ is *undecidable* for timed automata. The proof reduces from the halting problem for two-counter machines, encoding counter values as clock differences.

This is a sharp contrast with finite automata. Determinism, here, is genuinely restrictive: deterministic timed automata are strictly less expressive than nondeterministic ones, and no algorithm decides whether a given nondeterministic timed automaton has a deterministic equivalent.

=== One-Clock Timed Automata

*Theorem (Ouaknine--Worrell 2004).* Language inclusion is *decidable* (and *NSPACE*$(n^2)$-complete) for *one-clock* timed automata over infinite alphabets, and for finite-word semantics. With two clocks, undecidability returns.

The proof relies on a well-quasi-order on configurations of a region automaton augmented with a counter tracking unmatched obligation tokens; decidability follows from Higman's lemma applied to encoded configurations.

=== Event-Clock Automata

The undecidability of inclusion makes timed automata a problematic specification formalism. *Event-clock automata* (Alur--Fix--Henzinger 1999) restore determinizability by replacing arbitrary clocks with two distinguished families:

- *Recorder clocks* $x_a$ for each $a in Sigma$: $x_a$ measures time since the last occurrence of $a$.
- *Predictor clocks* $y_a$: $y_a$ measures time *until* the next occurrence of $a$ (a non-causal feature requiring symbolic resolution).

*Theorem (Alur--Fix--Henzinger 1999).* Event-clock automata are *determinizable* and *closed under all Boolean operations*. Inclusion is PSPACE-complete.

The trade-off: event-clock automata are strictly less expressive than general timed automata. They form the timed analogue of the variety of regular languages closed under complementation, with cleaner algebraic structure but reduced modelling power.

== Timed Games

A *timed game* (Asarin--Maler--Pnueli--Sifakis 1998; Maler--Pnueli--Sifakis 1995) is a timed automaton whose actions are partitioned into *controllable* $Sigma_c$ and *uncontrollable* $Sigma_u$. The controller chooses a strategy that maps configurations to (delay, controllable-action) pairs; the environment may pre-empt with any enabled $Sigma_u$ action at any moment.

*Reachability game.* Decide if the controller has a strategy to force the system into a target set $T subset.eq L$.

*Theorem (Asarin--Maler--Pnueli--Sifakis 1998).* The reachability and safety control problems for timed games are *EXPTIME-complete*.

*Algorithmic content.* The fixed-point computation is performed on zones with a *controllable-predecessor* operator $"Pred"_t^c(W) = { (l, v) | exists d gt.eq 0. exists a in Sigma_c. dots }$ defined symbolically over DBMs (Cassez--David--Fleury--Larsen--Lime 2005). The tool UPPAAL-TIGA implements this for safety, reachability, and Büchi objectives.

== Tools: UPPAAL, Kronos, RED, TChecker

*UPPAAL* (Larsen--Pettersson--Yi 1997, Aalborg/Uppsala) is the dominant model checker for timed automata. Its core data structure is DBM with $"LU"$-abstraction; it implements a forward symbolic exploration with subsumption check and supports a CTL-like query language with bounded-liveness.

*Kronos* (Yovine 1997, VERIMAG) was an earlier symbolic model checker emphasizing backward analysis and TCTL.

*RED* (Wang 2004) implements *region-encoding diagrams*, a BDD-style data structure for clock regions.

*TChecker* (Hérault--Point--Robbe 2019) is a modern reimplementation with pluggable abstractions, used in research on more aggressive subsumption.

== Hybrid Automata

A *hybrid automaton* (Alur--Courcoubetis--Henzinger--Ho 1992; Henzinger 1996) generalizes timed automata by replacing the rigid "clocks tick at rate 1" semantics with arbitrary continuous dynamics in each location.

*Definition (Hybrid Automaton).* A hybrid automaton is a tuple
$ cal(H) = (L, L_0, X, "Init", "Inv", "Flow", E, "Jump", Sigma, "Lab") $
where

- $L, L_0$ are locations and initial locations (as for TA),
- $X = {x_1, dots, x_n}$ is a finite set of *continuous variables*,
- $"Init"(l), "Inv"(l), "Flow"(l) subset.eq RR^X$ (or, more typically, $"Flow"(l)$ is a relation on $RR^X times RR^X$ giving allowed $(x, dot(x))$ pairs),
- $E subset.eq L times L$ is a set of edges, with $"Jump"(e) subset.eq RR^X times RR^X$ relating pre- and post-jump values,
- $"Lab" : E arrow.r Sigma$ labels jumps.

A run alternates *continuous evolutions* -- absolutely continuous trajectories $xi : [0, delta] arrow.r RR^X$ with $xi(t) in "Inv"(l)$ and $(xi(t), dot(xi)(t)) in "Flow"(l)$ for almost every $t$ -- and *discrete jumps* fired across edges whose guard is satisfied.

=== Linear Hybrid Automata

A *linear hybrid automaton* (LHA) restricts:

- $"Flow"(l) = { dot(x) | A_l dot(x) "≺"b_l }$: polyhedral constraints on derivatives;
- $"Inv"(l), "Init"(l), "Jump"(e)$: convex polyhedra (or unions thereof);
- Jumps reset some variables to constants or affine combinations.

LHA include *timed automata* (each clock is a variable with $dot(x) = 1$), *multi-rate automata* ($dot(x) = k_l$ varies per location), and *rectangular automata* (intervals on rates).

*Theorem (Henzinger--Kopke--Puri--Varaiya 1998).* Reachability for LHA is *undecidable* in general. The undecidability holds already for *2-rate timed automata* with rates $1$ and $2$.

The technique encodes a two-counter machine using two variables with different rates; the difference of variables stores a counter. Decrement, increment, and zero-test become reachability questions in a constructed LHA.

=== Rectangular Hybrid Automata

A *rectangular hybrid automaton* (RHA) restricts further: each variable evolves in an interval $dot(x) in [a_l^x, b_l^x]$ depending only on $l$ (no coupling), and guards/invariants are rectangular (each constraint involves a single variable).

*Definition (Initialized RHA).* An RHA is *initialized* if every jump that changes the flow interval of a variable $x$ also resets $x$ to a star.op value (i.e. $x$'s history is forgotten).

*Theorem (Henzinger--Kopke--Puri--Varaiya 1998).* Reachability for *initialized* rectangular hybrid automata is *decidable* (PSPACE-complete) by reduction to a multi-rate region automaton.

*Theorem (HKPV 1998).* Reachability for *uninitialized* RHA -- equivalently, for *stopwatch automata* (clocks with rates in ${0, 1}$ that can be paused without reset) -- is *undecidable*.

=== O-Minimal Hybrid Systems

A theory $T$ is *o-minimal* (van den Dries) if every definable subset of the real line is a finite union of points and intervals. The theory of real closed fields ($"Th"(RR, +, dot, 0, 1, <)$) and the theory $RR_(exp)$ (with exponentiation, Wilkie 1996) are o-minimal.

*Theorem (Lafferriere--Pappas--Sastry 2000).* For *o-minimal* hybrid systems -- systems where the flow in each location is a definable family of trajectories in an o-minimal expansion of the reals -- reachability is *decidable*, provided every discrete transition *resets* the continuous state (so locations are independent).

The decidability proof leverages the *cell decomposition theorem* for o-minimal structures: definable sets admit a finite partition into cells with uniformly bounded combinatorial complexity, yielding a finite bisimulation quotient.

=== Verification Tools for Hybrid Automata

- *HyTech* (Henzinger--Ho--Wong-Toi 1997): symbolic model checker for LHA, uses polyhedral computations (Halbwachs' library). Exact but limited to small examples.
- *PHAVer* (Frehse 2005): improves HyTech with widening and better polyhedral arithmetic.
- *SpaceEx* (Frehse--Le Guernic--Donzé--Cotton--Ray--Lebeltel--Ripado--Girard--Dang--Maler 2011): scalable reachability for *linear* hybrid systems using *support functions* and *Le Guernic--Girard* algorithm.
- *Flow\** (Chen--Ábrahám--Sankaranarayanan 2013): handles *nonlinear* ODEs via *Taylor models* with rigorous error bounds.
- *dReach* / *dReal* (Gao--Kong--Clarke 2013): $delta$-decision procedures over the reals with trigonometric and exponential functions; decides $delta$-reachability via SMT-modulo-ODE.

== Decidability Frontier: A Summary Table

```text
   model                          reachability     language inclusion
   -----                          ------------     ------------------
   timed automaton                PSPACE-c         undecidable
   1-clock TA                     NLOGSPACE        NSPACE(n^2)-c
   event-clock automaton          PSPACE-c        PSPACE-c (determ.)
   stopwatch automaton            undecidable      undecidable
   initialized rect. HA           PSPACE-c         undecidable
   linear hybrid automaton        undecidable      undecidable
   o-minimal HA (reset jumps)     decidable        open in general
```

The pattern: any continuous coupling between variables that retains state across jumps tends to encode counters; resets and rate-1 clocks tame this. The decidability proofs are essentially constructions of *finite bisimulation quotients*; the undecidability proofs are essentially encodings of two-counter machines.

== Region Construction: Worked Detail

Let $cal(A)$ have two clocks $x, y$ with $c_x = 2, c_y = 1$. The regions partition the quadrant $[0, oo)^2$ into:

```text
   "below max" zone: 0 <= x <= 2,  0 <= y <= 1
   "x saturated":    x > 2,        0 <= y <= 1
   "y saturated":    0 <= x <= 2,  y > 1
   "both saturated": x > 2, y > 1   (single region)
```

In the below-max zone, regions are:

- *Corner points* $(i, j)$ with $0 lt.eq i lt.eq 2, 0 lt.eq j lt.eq 1$: $3 dot 2 = 6$ points;
- *Open horizontal segments* $i < x < i+1, y = j$ and *vertical* $x = i, j < y < j+1$: $2 dot 2 + 3 dot 1 = 7$;
- *Open unit triangles* split by the diagonal $x - y = i - j$ (constant): for each unit square there are two triangles plus the open diagonal segment, $2 + 2 = 4$ pieces per cell; with $2 dot 1 = 2$ unit cells, $8$ pieces.

Adding the saturated zones gives $6 + 7 + 8 + 3 + 3 + 1 = 28$ regions per location. The number scales as $|X|! 2^|X| product (c_x + 1)$.

== Symbolic Reachability Pseudocode

```python
def reach(A):
    # A = (L, L0, Sigma, X, E, Inv)
    Waiting = [(l0, zero_zone(X) & Inv(l0)) for l0 in A.L0]
    Passed  = []
    while Waiting:
        (l, Z) = Waiting.pop()
        if any(l == lp and Z <= Zp for (lp, Zp) in Passed):
            continue
        Passed.append((l, Z))
        # delay successor
        Zd = (future(Z) & Inv(l))
        for (lg, g, a, r, lp) in A.E if lg == l:
            Zg = (Zd & guard_to_zone(g))
            if not empty(Zg):
                Zp = reset(Zg, r) & Inv(lp)
                if not empty(Zp):
                    Zp = LU_normalize(Zp, A)
                    Waiting.append((lp, Zp))
    return Passed
```

The `LU_normalize` step is what guarantees termination. Without it, repeated incrementing of an unbounded clock would generate infinitely many distinct zones. The subsumption check `Z <= Zp` and the choice of abstraction together control state-space explosion in practice.

== Liveness and Timed Büchi Acceptance

A *Timed Büchi Automaton* (TBA) has a designated set $F subset.eq L$; a run is accepting if it visits $F$ infinitely often *and* is *non-Zeno*, i.e. the sequence of timestamps diverges. The non-Zeno requirement excludes pathological behaviours like infinitely many actions in a bounded interval.

*Theorem (Alur--Dill 1994).* Emptiness of TBAs is *PSPACE-complete*, decided by searching for a *fair cycle* in the region automaton -- a cycle that visits $F$ and along which some clock is reset, ensuring time can elapse.

*Strong non-Zenoness* is a stricter syntactic condition: every cycle in the region automaton must contain a state where some clock $x$ has $v(x) gt.eq 1$ and an edge resetting $x$. UPPAAL relies on user-supplied leads-to properties combined with structural fairness to check liveness.

== TCTL Model Checking

*Timed Computation Tree Logic* (Alur--Courcoubetis--Dill 1990) extends CTL with subscripted modalities:

$ phi ::= p | not phi | phi and phi | exists phi_1 U_("≺" c) phi_2 | forall phi_1 U_("≺" c) phi_2 $

Read $exists phi_1 U_(lt.eq 5) phi_2$ as there is a run along which $phi_1$ holds until $phi_2$ holds, within $5$ time units.

*Theorem (Alur--Courcoubetis--Dill 1993).* TCTL model checking for timed automata is *PSPACE-complete*. The algorithm augments the automaton with a star.op observer clock for each subformula and reduces to repeated reachability on a region/zone graph.

== Beyond Reachability: Parametric and Weighted Extensions

=== Parametric Timed Automata

*Parametric timed automata* (Alur--Henzinger--Vardi 1993) allow constraints $x "≺"p$ for parameter $p$. The *emptiness problem* -- does there exist a parameter valuation making a target reachable -- is *undecidable* with $gt.eq 3$ parametric clocks. *L/U automata* (Hune--Romijn--Stoelinga--Vaandrager 2002), where each parameter appears only as a lower or only as an upper bound, regain decidability for emptiness.

=== Weighted Timed Automata

*Weighted timed automata* (Alur--La Torre--Pappas 2001; Behrmann--Fehnker--Hune--Larsen--Pettersson--Romijn--Vaandrager 2001) attach a cost rate $r(l)$ to each location and discrete costs to edges. The *optimal-reachability* problem -- find the minimum-cost run reaching a target -- is *PSPACE-complete*. The *bounded-cost reachability* and most natural extensions to multiple cost variables are *undecidable* with $gt.eq 3$ variables.

The connection to weighted automata (cf. _Weighted and Probabilistic Automata_) is intimate: a weighted TA is a TA whose timed runs are evaluated in the tropical semiring $(RR union {oo}, min, +)$ along trajectories.

== Complexity Landscape

```text
   problem                                         complexity
   -------                                         ----------
   TA reachability                                 PSPACE-complete
   TA reachability, 1 clock                        NLOGSPACE-complete
   TA reachability, 3 clocks                       PSPACE-hard
   TA universality / inclusion                     undecidable
   TA inclusion, 1-clock, finite words             NSPACE(n^2)-complete
   event-clock automata inclusion                  PSPACE-complete
   timed games (reach/safety)                      EXPTIME-complete
   weighted TA optimal reach                       PSPACE-complete
   weighted TA, multi-cost reach                   undecidable (>=3 vars)
   parametric TA emptiness                         undecidable (>=3 par clks)
   initialized RHA reachability                    PSPACE-complete
   stopwatch / 2-rate TA reachability              undecidable
```

== Discussion: Why Dense Time?

Discrete-time formalisms can simulate dense time at the cost of an unbounded discretization parameter. The Alur--Dill contribution is to demonstrate that *dense time is not harder than discrete time for reachability*: the region construction gives a uniform finite quotient whose size depends on syntactic constants, not on any chosen time granularity. This is what makes timed automata the canonical model for *quantitative* real-time verification: properties are stated and verified at the same semantic level at which they are reasoned about by engineers, without an artificial intermediate discretization.

The cost is paid in expressiveness boundaries: closure under complementation fails, language inclusion is undecidable, and any natural strengthening of the formalism (stopwatches, two-counter rates, multi-cost weights) crashes into undecidability. The success of UPPAAL in industrial verification of protocols and embedded controllers shows that, within those boundaries, the model captures enough engineering reality to be useful.

== Exercises

1. Prove that region equivalence is preserved by time elapse: if $v tilde v'$, then there exists $d' gt.eq 0$ such that $v + d tilde v' + d'$ for any $d gt.eq 0$ leading to a successor region.
2. Construct a timed automaton with $2$ clocks whose region automaton has at least $50$ regions per location. Compare with the zone reachability tree.
3. Show that the language $L = { (a, t_1)(a, t_2) | t_2 - t_1 in QQ }$ is *not* timed-regular.
4. Implement Floyd--Warshall on DBMs and verify on a $3$-clock example that the canonical form satisfies the triangle inequality.
5. Encode a $3$-rectangle initialized RHA modelling a thermostat with heating, cooling, and idle locations; compute the reachable zone of (temperature, time) pairs.
6. Argue why $cal(C)$-closure is unsound when diagonal constraints $x - y "≺"c$ appear with $c$ exceeding the per-clock maximum.

== Extended Topic: Time-Abstract Bisimulation and Quotient Constructions

A *time-abstract bisimulation* on a timed transition system $(S, arrow.r)$ is an equivalence $tilde$ such that whenever $s_1 tilde s_2$:

- For every $a in Sigma$ and $s_1 arrow.r^a s_1'$, there exists $s_2'$ with $s_2 arrow.r^a s_2'$ and $s_1' tilde s_2'$;
- For every $d gt.eq 0$ and $s_1 arrow.r^d s_1'$, there exist $d' gt.eq 0$ and $s_2'$ with $s_2 arrow.r^(d') s_2'$ and $s_1' tilde s_2'$.

Note the *abstraction* over the delay duration: $d$ and $d'$ need not coincide; only their qualitative effect on regions must match. The region equivalence is the *coarsest* time-abstract bisimulation that respects the location and the per-clock $c_x$ bounds.

*Theorem (Tripakis--Yovine 2001).* Every finite time-abstract bisimulation quotient of a timed automaton's transition system refines the region quotient. Coarser symbolic representations (zones, $"LU"$-abstractions) do *not* in general yield bisimulation-respecting quotients, only simulation-respecting ones; this suffices for reachability and safety but not for branching-time logics like TCTL with $exists$ over arbitrary futures.

== Extended Topic: Updatable Timed Automata

*Updatable timed automata* (Bouyer--Dufourd--Fleury--Petit 2004) generalize Alur--Dill resets to *updates* of the form $x := y + c$, $x := c$, $x in [a, b]$, or $x := c y$.

*Theorem (BDFP 2004).* Reachability for updatable timed automata is

- *decidable* (PSPACE-complete) for updates $x := c$ (constant), $x := y$, $x := x + 1$ under syntactic restrictions;
- *undecidable* for arbitrary $x := y + c$ with $c < 0$, by reduction from two-counter machines.

The classification of decidable update fragments forms a non-trivial lattice; see the BDFP taxonomy table.

== Extended Topic: Timed Pushdown Automata

*Timed pushdown automata* (Bouajjani--Echahed--Robbana 1994; Abdulla--Atig--Stenman 2012) combine clocks and a pushdown stack.

*Theorem (Abdulla--Atig--Stenman 2012).* Reachability for *dense-timed* pushdown automata, where stack symbols carry ages, is *EXPTIME-complete*. The construction uses a generalization of the region construction combined with a snapshot-based abstraction of the stack.

This enables verification of recursive timed programs and time-bounded asynchronous protocols.

== Extended Topic: Hybrid Automata with Inputs and Outputs

The original hybrid automaton model is *closed*: all dynamics intrinsic. *Hybrid I/O automata* (Lynch--Segala--Vaandrager 2003) distinguish input variables (under environment control), output variables (under system control), and internal variables, with composition defined by synchronization on shared variables.

This compositional framework underpins formal models for cyber-physical systems and is implemented in PVS-libraries and the IOA toolkit.

== Extended Topic: Approximate Bisimulation for Hybrid Systems

For nonlinear hybrid systems, exact bisimulation is rarely computable. *Approximate bisimulation* (Girard--Pappas 2007) replaces equality of trajectories with proximity:

*Definition.* A symmetric relation $cal(R)$ is an *$epsilon$-approximate bisimulation* if $(x, y) in cal(R)$ => $|x - y| lt.eq epsilon$ and every transition from one side is matched within $cal(R)$ from the other.

*Theorem (Girard--Pappas 2007).* For *incrementally stable* linear systems $dot(x) = A x + B u$ with $A$ Hurwitz, finite $epsilon$-approximate bisimulations are computable, yielding controllers with quantifiable robustness margins.

Tools: *Pessoa* (Mazo--Davitian--Tabuada 2010) and *SCOTS* (Rungger--Zamani 2016) synthesize symbolic controllers from approximate bisimulations.

== Extended Topic: Bounded Model Checking of Hybrid Systems

For undecidable hybrid models, *bounded model checking* trades completeness for tractability: search for counterexamples up to depth $k$, encoded as an SMT formula over reals with transcendental functions.

*$delta$-decidability* (Gao--Avigad--Clarke 2012): for the first-order theory of reals with computable functions (including $exp, sin, cos$, solutions to Lipschitz ODEs), there is an algorithm that for any $delta > 0$ either certifies a formula or its $delta$-weakening.

Tools: *dReal* (Gao--Kong--Clarke 2013), *iSAT-ODE* (Eggers--Fränzle--Herde 2008). Used in cardiac-cell-model verification (Kong et al.), autonomous-vehicle planning.

== Extended Topic: Timed Automata with Energy Constraints

*Energy automata* (Bouyer--Fahrenberg--Larsen--Markey 2008) annotate edges with energy deltas $w in ZZ$; the energy level must stay non-negative.

*Theorem (BFLM 2008).* The *lower-bound* energy problem -- can the energy level be kept $gt.eq 0$ forever? -- is *PSPACE-complete* for $1$-clock energy timed automata, *undecidable* with $gt.eq 2$ clocks (without restrictions) but recovers *EXPTIME-completeness* under structural assumptions.

This models battery-powered systems, scheduling with budget, and the *energy parity games* studied in controller synthesis.

== Extended Topic: Compositional Verification

UPPAAL's *modular timed automata* via parallel composition $cal(A)_1 || cal(A)_2$ synchronize on shared actions and run other actions independently. The product construction has state space $L_1 times L_2$ and clock set $X_1 union.dot X_2$ (disjoint copies). Compositional reasoning uses *assume-guarantee* contracts: prove $cal(A)_1 || E_2 models phi$ and $E_1 || cal(A)_2 models psi$ where $E_i$ are abstract environments derived from contracts.

Compositional verification of timed systems remains an active research area; tools like *MoChA* and the *ECDAR* framework (David--Larsen--Legay--Nyman--Wąsowski 2010) implement variants based on *timed I/O automata refinement*.

== Extended Topic: Counter-Example Guided Abstraction Refinement

CEGAR for timed automata (Henzinger--Jhala--Majumdar--Sutre 2002; Dierks--Kupferschmid--Larsen 2007):

1. Begin with the *location-only* abstraction (collapse all clock-valuations).
2. Model-check the abstract system; if safe, return; else extract spurious counterexample.
3. Refine by reintroducing relevant clock distinctions (predicates over clock values).
4. Repeat.

This is dramatically more efficient than full-zone exploration for properties depending on few clocks.

== Worked Example: Train--Gate Controller (Henzinger--Manna--Pnueli)

The classic example: a train approaches a gate; the controller must lower the gate before the train enters the crossing. Train timing constraints: from approach signal to crossing entry, at least $300 s$ and at most $500 s$. Gate timing: lower in at most $100 s$, raise in at most $100 s$. Safety: gate down whenever train in crossing.

Modelled as $3$ parallel TAs (Train, Gate, Controller) synchronizing on `approach, exit, lower, raise`. The product has $O(10)$ symbolic states and a property `AG (train in crossing arrow.r "gate down")` decided in milliseconds by UPPAAL. Replacing the upper-bound constraint $500 s$ by parametric $p$ and asking for what $p$ is the system safe? leads to parametric timed automata analysis.

== Worked Example: Bouncing Ball (Hybrid Automaton)

A ball with position $h gt.eq 0$ and velocity $v$ obeys $dot(h) = v, dot(v) = -g$ during free fall; on impact ($h = 0, v < 0$) it bounces with coefficient $c in (0, 1)$: $v := -c v$.

```text
   Loc FALL, Inv: h >= 0
       Flow: dh/dt = v, dv/dt = -g
       Guard h = 0 and v < 0
          / Jump: v := -c v
          v
       (back to FALL)
```

This is a *Zeno* system: in finite physical time, infinitely many bounces occur (the period decreases geometrically by factor $c$). Reachability analysis must handle Zeno detection; SpaceEx terminates with an accumulation point warning when the state-space trajectory's diameter falls below tolerance.

== Worked Example: Thermostat with Hysteresis

```text
   Loc HEATING, Inv: T <= 22
       Flow: dT/dt = K(T_outside - T) + Q_heater
       Guard T = 22 / Jump: -            ->   Loc IDLE
   Loc IDLE, Inv: T >= 18
       Flow: dT/dt = K(T_outside - T)
       Guard T = 18 / Jump: -            ->   Loc HEATING
```

For *rectangular* over-approximations $dot(T) in [a_l, b_l]$ per location, this is an initialized RHA; reachability is decidable. For the exact linear ODE, the system is a *linear hybrid system* requiring SpaceEx or Flow\* for sound numerical reachability.

== References (Selected)

- R. Alur, D. Dill. *A Theory of Timed Automata*. TCS 126(2), 1994.
- R. Alur, C. Courcoubetis, T. A. Henzinger, P. Ho. *Hybrid Automata: An Algorithmic Approach to the Specification and Verification of Hybrid Systems*. LNCS 736, 1992.
- C. Courcoubetis, M. Yannakakis. *Minimum and Maximum Delay Problems in Real-Time Systems*. FMSD 1992.
- T. A. Henzinger, P. W. Kopke, A. Puri, P. Varaiya. *What's Decidable about Hybrid Automata?* JCSS 57, 1998.
- G. Lafferriere, G. J. Pappas, S. Sastry. *O-Minimal Hybrid Systems*. MCSS 13(1), 2000.
- C. Daws, S. Tripakis. *Model Checking of Real-Time Reachability Properties Using Abstractions*. TACAS 1998.
- J. Ouaknine, J. Worrell. *On the Language Inclusion Problem for Timed Automata*. LICS 2004.
- R. Alur, L. Fix, T. A. Henzinger. *Event-Clock Automata: A Determinizable Class of Timed Automata*. TCS 1999.
- E. Asarin, O. Maler, A. Pnueli, J. Sifakis. *Controller Synthesis for Timed Automata*. SSC 1998.
- K. G. Larsen, P. Pettersson, W. Yi. *UPPAAL in a Nutshell*. STTT 1(1), 1997.
- G. Frehse et al. *SpaceEx: Scalable Verification of Hybrid Systems*. CAV 2011.
