#import "../template.typ": overbar, xref

= Propositional and First-Order Logic <propositional-and-fol>

Logic is the substrate of formal methods: every model checker, $"SMT"$ solver, and theorem prover ultimately manipulates formulas in some logical language. This chapter develops propositional logic and first-order logic (FOL) at the level needed to read papers on decision procedures, define semantics of program logics, and understand what a tool like Z3 or Coq is actually computing. We focus on syntax, semantics, proof systems, and the algorithmic landscape — decidability, complexity, and normal forms.

*See also:* #xref("formal-methods", "sat-and-smt", label: "SAT and SMT"), #xref("formal-methods", "model-checking", label: "Model Checking"), #xref("formal-methods", "theorem-proving", label: "Theorem Proving"), #xref("programming-languages", "operational-semantics", label: "Operational Semantics") (programming-languages), _Omega-Automata_ (programming-languages)

== Propositional Logic: Syntax

The language $"PL"$ is built from a countable set of propositional variables $p, q, r, ...$, the constants $top$ (true) and $bot$ (false), and the connectives $not, and, or, ->, <->$. Well-formed formulas are generated by the grammar

$ phi ::= p | top | bot | not phi | phi and phi | phi or phi | phi -> phi | phi <-> phi $

We treat $-> $ as right-associative and assign the usual precedence $not > and > or > -> $. A *literal* is a variable or a negated variable. A *clause* is a disjunction of literals; a *cube* is a conjunction of literals.

== Semantics and Entailment

An *assignment* (or interpretation) $nu: "Var" -> {0, 1}$ extends compositionally to all formulas. We write $nu models phi$ when $[|phi|]_nu = 1$.

#table(
  columns: (auto, auto),
  [*Formula*], [*Truth condition*],
  [$nu models p$], [$nu(p) = 1$],
  [$nu models not phi$], [$nu cancel(models) phi$],
  [$nu models phi and psi$], [$nu models phi$ and $nu models psi$],
  [$nu models phi or psi$], [$nu models phi$ or $nu models psi$],
  [$nu models phi -> psi$], [if $nu models phi$ then $nu models psi$],
)

A formula is *satisfiable* if some $nu$ satisfies it; *valid* (a tautology) if every $nu$ does; *unsatisfiable* otherwise. *Entailment* $Gamma models phi$ holds when every model of every formula in $Gamma$ also models $phi$. The fundamental duality of propositional reasoning:

$ Gamma models phi quad <==> quad Gamma union {not phi} text(" is unsatisfiable") $

This is why $"SAT"$ solvers (chapter on #xref("formal-methods", "sat-and-smt", label: "SAT and SMT")) are universal engines for propositional reasoning: validity, entailment, equivalence, and minimum-cost assignment all reduce to $"SAT"$ or its weighted variant MaxSAT.

== Normal Forms

*Negation normal form* (NNF) pushes negations to literals using De Morgan's laws and double-negation elimination. *Conjunctive normal form* (CNF) is a conjunction of clauses; *disjunctive normal form* (DNF) is a disjunction of cubes. CNF is the standard input format for $"SAT"$ solvers (DIMACS).

*Naive CNF conversion blows up.* Distributing $or$ over $and$ can yield exponential size: $(p_1 and q_1) or ... or (p_n and q_n)$ has $2^n$ clauses in CNF. The *Tseitin transformation* avoids this by introducing fresh variables for subformulas, producing an equisatisfiable CNF of linear size.

```python
# Tseitin CNF: equisatisfiable linear-size conversion
from itertools import count

def tseitin(phi):
    """phi: nested tuple ('and',a,b), ('or',a,b), ('not',a), or str (var).
       Returns (top_var, clauses) where clauses is a list of frozensets of
       signed literals (positive int = var, negative = negation)."""
    fresh = count(1)
    var_of = {}
    def vid(name):
        if name not in var_of:
            var_of[name] = next(fresh)
        return var_of[name]
    clauses = []
    def walk(node):
        if isinstance(node, str):
            return vid(node)
        op = node[0]
        if op == 'not':
            a = walk(node[1])
            return -a
        a, b = walk(node[1]), walk(node[2])
        t = next(fresh)
        if op == 'and':
            # t <-> (a /\ b)
            clauses.append(frozenset([-t,  a]))
            clauses.append(frozenset([-t,  b]))
            clauses.append(frozenset([ t, -a, -b]))
        elif op == 'or':
            # t <-> (a \/ b)
            clauses.append(frozenset([-t,  a,  b]))
            clauses.append(frozenset([ t, -a]))
            clauses.append(frozenset([ t, -b]))
        return t
    top = walk(phi)
    clauses.append(frozenset([top]))   # assert phi
    return top, clauses

# Example: ((p /\ q) \/ (not r))
phi = ('or', ('and','p','q'), ('not','r'))
top, cls = tseitin(phi)
# Output is in DIMACS form modulo printing.
```

The cost: $O(|phi|)$ new variables and $O(|phi|)$ clauses, but with extra variables that the solver internalizes. Modern preprocessors (SatELite, the Tseitin elimination pass in CaDiCaL) often shrink the resulting formula again.

== Proof Systems for Propositional Logic

Three traditional proof systems are worth knowing because they correspond to different verification engines.

*Resolution.* From clauses $C union {p}$ and $D union {not p}$ derive $C union D$. A propositional CNF is unsatisfiable iff the empty clause $square$ is derivable by resolution. CDCL $"SAT"$ solvers implicitly construct resolution refutations.

*Natural deduction* and *sequent calculus.* The proof-theoretic counterparts used in proof assistants. A sequent $Gamma tack.r Delta$ asserts that if every formula in $Gamma$ is true, then some formula in $Delta$ is. Gentzen's cut-elimination theorem says proofs can be normalized — the engine behind Coq's `auto` and Isabelle's `blast`.

*Tableaux.* A refutation method that builds a tree by branching on disjunctions and signing formulas with $T$/$F$. Useful pedagogically and in some description-logic reasoners.

```text
Resolution refutation of  (p \/ q) /\ (not p \/ r) /\ (not q \/ r) /\ (not r)

  C1: p \/ q
  C2: not p \/ r
  C3: not q \/ r
  C4: not r

  C2, C4  |-  not p                (resolve on r)
  C3, C4  |-  not q                (resolve on r)
  C1, (not p) |-  q                (resolve on p)
  q, (not q) |-  []                (resolve on q)   <-- empty clause
```

== Decision Procedures and Complexity

Propositional satisfiability is the original NP-complete problem (Cook 1971; Levin 1973). Yet modern CDCL solvers handle industrial instances with $10^7$ variables. The chapter on #xref("formal-methods", "sat-and-smt", label: "SAT and SMT") explains how. For now, the relevant complexity landmarks:

#table(
  columns: (auto, auto, auto),
  [*Problem*], [*Complexity*], [*Tool*],
  [Propositional SAT], [NP-complete], [MiniSat, CaDiCaL, Kissat],
  [Validity in PL], [coNP-complete], [via SAT on the negation],
  [\#SAT (model counting)], [\#P-complete], [c2d, sharpSAT, Ganak],
  [QBF (quantified Boolean)], [PSPACE-complete], [CAQE, DepQBF],
  [2-SAT (binary clauses)], [P (linear time)], [Aspvall-Plass-Tarjan SCC],
  [Horn-SAT], [P (linear time)], [unit propagation],
  [XOR-SAT], [P (Gaussian elimination)], [linear algebra over $"GF"(2)$],
)

The polynomial fragments (2-SAT, Horn-SAT, XOR-SAT) underlie *theory solvers* in $"SMT"$ — they decide specific theories without invoking a full $"SAT"$ search.

== First-Order Logic: Syntax

FOL extends $"PL"$ with *terms* (constants, variables, function applications $f(t_1, ..., t_n)$) and *atomic formulas* $P(t_1, ..., t_n)$ where $P$ is an $n$-ary predicate symbol. Quantifiers $forall$ and $exists$ bind variables. A *signature* $Sigma = (F, P)$ lists function and predicate symbols with arities.

$ phi ::= P(t_1, ..., t_n) | t_1 = t_2 | not phi | phi and phi | phi or phi | forall x. phi | exists x. phi $

Free vs bound variables: $forall x. P(x, y)$ has $y$ free and $x$ bound. *Closed* formulas (no free variables) are *sentences*. A *theory* is a set of sentences closed under entailment.

== Structures and Semantics

A *structure* $cal(M) = (D, I)$ has a non-empty domain $D$ and an interpretation $I$ assigning each $n$-ary function symbol $f in F$ a function $I(f): D^n -> D$ and each predicate $P in P$ a relation $I(P) subset.eq D^n$. An *assignment* $nu: "Var" -> D$ gives meaning to free variables; together they define $[|t|]_(cal(M), nu) in D$ and $cal(M), nu models phi$.

Quantifiers range over $D$:

$ cal(M), nu models forall x. phi quad <==> quad text("for every ") d in D, cal(M), nu[x |-> d] models phi $

A sentence $phi$ is *satisfiable* if some structure satisfies it; *valid* if every structure does. *Entailment* is again duality with unsatisfiability.

== Skolemization and Prenex Form

*Prenex normal form* puts all quantifiers at the front: $Q_1 x_1. Q_2 x_2. ... . psi$ with $psi$ quantifier-free. Then *Skolemization* removes existentials by introducing fresh function symbols depending on the surrounding universals:

$ forall x. exists y. P(x, y) quad ~> quad forall x. P(x, f(x)) $

The Skolemized formula is *equisatisfiable* (not equivalent) to the original. Skolem normal form is the input to resolution-based first-order provers (Vampire, E, SPASS).

== Resolution and Unification

Robinson's *resolution* for FOL combines propositional resolution with *unification*. The most general unifier (MGU) of $P(x, f(y))$ and $P(g(z), f(a))$ is ${x |-> g(z), y |-> a}$. Two clauses with literals $L_1$ and $not L_2$ resolve when their atoms unify.

```python
# Robinson unification (occurs-check included)
def unify(s, t, theta=None):
    theta = {} if theta is None else dict(theta)
    s, t = walk(s, theta), walk(t, theta)
    if s == t: return theta
    if is_var(s): return bind(s, t, theta)
    if is_var(t): return bind(t, s, theta)
    if is_compound(s) and is_compound(t) and s[0] == t[0] and len(s) == len(t):
        for a, b in zip(s[1:], t[1:]):
            theta = unify(a, b, theta)
            if theta is None: return None
        return theta
    return None

def walk(x, theta):
    while is_var(x) and x in theta: x = theta[x]
    return x

def bind(v, x, theta):
    if occurs(v, x, theta): return None     # occurs-check
    theta[v] = x
    return theta
```

The Knuth-Bendix completion algorithm and superposition calculus extend this to equational reasoning — the engine of modern automated theorem provers.

== Decidability Landscape

FOL is *undecidable* but *semi-decidable*: there is a procedure that halts on every valid sentence (Gödel 1930), but no procedure halts on every invalid one (Church-Turing 1936). The boundary between decidable and undecidable fragments is mapped finely:

#table(
  columns: (auto, auto, auto),
  [*Fragment*], [*Decidability*], [*Complexity*],
  [Propositional logic], [Decidable], [NP-complete],
  [Monadic FOL (unary predicates only)], [Decidable], [NEXPTIME],
  [Two-variable FOL ($"FO"^2$)], [Decidable], [NEXPTIME-complete],
  [Guarded fragment GF], [Decidable], [2EXPTIME],
  [Bernays-Schönfinkel ($exists^* forall^*$)], [Decidable], [NEXPTIME],
  [Presburger arithmetic], [Decidable], [doubly exponential],
  [Linear real arithmetic], [Decidable in P (LP)], [polynomial],
  [Theory of equality + UF], [Decidable], [polynomial],
  [Theory of arrays (basic)], [Decidable], [varies],
  [FOL (full)], [Semi-decidable], [---],
  [Peano arithmetic], [Not even semi-decidable for $not phi$], [---],
)

The decidable theories on the right column are exactly what $"SMT"$ solvers integrate via the *Nelson-Oppen combination* method (chapter on #xref("formal-methods", "sat-and-smt", label: "SAT and SMT")).

== Gödel's Theorems in One Page

For verification engineers, the practical consequences of Gödel's theorems are:

- *Completeness (1930):* FOL has a sound and complete proof system; every valid sentence is provable. This is what makes resolution-based provers work.
- *Incompleteness I (1931):* Any consistent recursively axiomatized theory extending Robinson arithmetic has true sentences it cannot prove. So Peano arithmetic, ZFC, Coq's calculus — none can prove their own consistency.
- *Incompleteness II:* Extends I: the consistency of such a theory cannot be proved within that same theory. Foundational systems for proof assistants (CIC, MLTT + universes) rely on meta-theoretic consistency proofs in stronger systems.

For day-to-day verification this means: total automation of unbounded program reasoning is impossible, which is why proof assistants exist alongside SMT solvers.

== Equality and Theories

Equality $=$ is treated as a logical symbol with reflexivity, symmetry, transitivity, and *congruence* ($t_1 = u_1, ..., t_n = u_n$ imply $f(overbar(t)) = f(overbar(u))$). The *theory of equality with uninterpreted functions* (EUF) is decided in polynomial time by *congruence closure* — the workhorse of every $"SMT"$ solver.

```text
Congruence closure example:

  Assume:  a = b,  f(a) = c,  g(b) = c,  g(a) != g(b)
  Goal:    UNSAT

  Initial partition: {a}, {b}, {c}, {f(a)}, {g(a)}, {g(b)}
  a = b           => merge {a, b}
  f(a) = c        => merge {f(a), c}
  g(b) = c        => merge {g(b), c, f(a)}
  congruence: a = b, so g(a) = g(b) => merge {g(a), g(b), c, f(a)}
  g(a) != g(b)    => contradiction (both in same class)
  UNSAT.
```

== Cross-References to Companion Volumes

The programming-languages volume treats *language theory* — automata on $omega$-words and trees, the $mu$-calculus, Courcelle's theorem — as the mathematics behind temporal specification. This volume treats logic algorithmically: how to *decide* it, how to *use* it to verify code. When you read _Omega-Automata_ (programming-languages volume) alongside our #xref("formal-methods", "model-checking", label: "Model Checking") chapter, the picture is complete: the automata are the spec language, the model-checking algorithms are the engine.

For the proof-theoretic side, `programming-languages/operational-semantics.typ` develops Hoare logic as a *language* for assertions about programs; our _Program Verification_ chapter develops the *tooling* — verification condition generation, $"SMT"$ discharge, separation logic, Iris.

== Further Reading

Enderton, H. (2001). #emph[A Mathematical Introduction to Logic.] Academic Press.

Shoenfield, J. (1967). #emph[Mathematical Logic.] Addison-Wesley.

Fitting, M. (1996). #emph[First-Order Logic and Automated Theorem Proving.] Springer.

Bradley, A., Manna, Z. (2007). #emph[The Calculus of Computation.] Springer.

Harrison, J. (2009). #emph[Handbook of Practical Logic and Automated Reasoning.] Cambridge.

Boolos, G., Burgess, J., Jeffrey, R. (2007). #emph[Computability and Logic.] Cambridge.

Robinson, J. A. (1965). "A Machine-Oriented Logic Based on the Resolution Principle." #emph[JACM].

Nelson, G., Oppen, D. (1980). "Fast Decision Procedures Based on Congruence Closure." #emph[JACM].
