#!/usr/bin/env python3
"""Generate chapters.yml from the current filesystem.

Preserves `status` and `last_reviewed_at` for entries that already exist in
chapters.yml; defaults new entries to status: draft.

Run from repo root: `python3 scripts/gen_manifest.py`
"""
from __future__ import annotations

import sys
from pathlib import Path

SUBJECTS = [
    "cloud-and-infrastructure",
    "coding",
    "compilers",
    "cpu-architecture",
    "cryptography-and-security",
    "data-engineering",
    "database",
    "distributed-systems",
    "embedded-and-realtime",
    "formal-methods",
    "gpu-architecture",
    "graphics-and-rendering",
    "linux-kernel",
    "llm",
    "machine-learning-foundations",
    "networking",
    "observability-and-sre",
    "operating-systems",
    "programming-languages",
    "quantum-computing",
    "computer-vision",
    "software-architecture",
    "performance-engineering",
    "numerical-computing",
    "web-and-browsers",
    "search-and-ir",
]


def count_words(p: Path) -> int:
    """Chapter size in words.

    Must stay consistent with scripts/lint_chapters.py: chapters wrap each
    paragraph onto one long line, so a line count measures paragraph style
    rather than substance, and churns on every reflow.
    """
    return len(p.read_text(encoding="utf-8", errors="replace").split())


def load_existing(path: Path) -> dict[tuple[str, str], dict]:
    if not path.exists():
        return {}
    try:
        import yaml  # type: ignore
    except ImportError:
        print("note: PyYAML not installed; existing chapters.yml not preserved", file=sys.stderr)
        return {}
    with path.open() as f:
        data = yaml.safe_load(f) or {}
    out: dict[tuple[str, str], dict] = {}
    for e in data.get("chapters", []):
        try:
            out[(e["subject"], e["slug"])] = e
        except (KeyError, TypeError):
            continue
    return out


def yaml_escape(s: str) -> str:
    # Conservative: only quote if needed.
    if any(c in s for c in ":#&*!|>'\"%@`") or s.strip() != s:
        return '"' + s.replace('"', '\\"') + '"'
    return s


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    out_path = root / "chapters.yml"
    existing = load_existing(out_path)

    lines: list[str] = []
    lines.append("# Auto-generated by scripts/gen_manifest.py.")
    lines.append("# Edit `status` and `last_reviewed_at` fields manually; rerun the")
    lines.append("# script after adding or removing chapter files. Other fields are")
    lines.append("# derived from the filesystem.")
    lines.append("chapters:")

    total = 0
    for subject in SUBJECTS:
        d = root / subject
        if not d.is_dir():
            continue
        # rglob, not iterdir: coding/advanced-java/*.typ ship in the
        # coding PDF (included via distributed-algorithms.typ) but were
        # absent from the manifest and the generated site.
        files = sorted(p for p in d.rglob("*.typ") if p.is_file())
        for p in files:
            slug = p.stem
            n = count_words(p)
            prev = existing.get((subject, slug), {})
            status = prev.get("status", "draft")
            reviewer = prev.get("reviewer", None)
            last_reviewed = prev.get("last_reviewed_at", None)
            lines.append(f"  - subject: {subject}")
            lines.append(f"    slug: {slug}")
            lines.append(f"    path: {p.relative_to(root).as_posix()}")
            lines.append(f"    words: {n}")
            lines.append(f"    status: {yaml_escape(status)}")
            if reviewer is not None:
                lines.append(f"    reviewer: {yaml_escape(str(reviewer))}")
            if last_reviewed is not None:
                lines.append(f"    last_reviewed_at: {yaml_escape(str(last_reviewed))}")
            total += 1

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path.relative_to(root)} ({total} chapters)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
