#!/usr/bin/env python3
"""Generate chapters.yml from the current filesystem.

Preserves `status` and `last_reviewed_at` for entries that already exist in
chapters.yml; defaults new entries to status: draft.

Run from repo root: `python3 scripts/gen_manifest.py`
"""
from __future__ import annotations

import sys
from pathlib import Path

SUBJECTS = [
    "coding",
    "cpu-architecture",
    "database",
    "gpu-architecture",
    "linux-kernel",
    "llm",
    "networking",
    "programming-languages",
]


def count_lines(p: Path) -> int:
    with p.open("rb") as f:
        return sum(1 for _ in f)


def load_existing(path: Path) -> dict[tuple[str, str], dict]:
    if not path.exists():
        return {}
    try:
        import yaml  # type: ignore
    except ImportError:
        print("note: PyYAML not installed; existing chapters.yml not preserved", file=sys.stderr)
        return {}
    with path.open() as f:
        data = yaml.safe_load(f) or {}
    out: dict[tuple[str, str], dict] = {}
    for e in data.get("chapters", []):
        try:
            out[(e["subject"], e["slug"])] = e
        except (KeyError, TypeError):
            continue
    return out


def yaml_escape(s: str) -> str:
    # Conservative: only quote if needed.
    if any(c in s for c in ":#&*!|>'\"%@`") or s.strip() != s:
        return '"' + s.replace('"', '\\"') + '"'
    return s


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    out_path = root / "chapters.yml"
    existing = load_existing(out_path)

    lines: list[str] = []
    lines.append("# Auto-generated by scripts/gen_manifest.py.")
    lines.append("# Edit `status` and `last_reviewed_at` fields manually; rerun the")
    lines.append("# script after adding or removing chapter files. Other fields are")
    lines.append("# derived from the filesystem.")
    lines.append("chapters:")

    total = 0
    for subject in SUBJECTS:
        d = root / subject
        if not d.is_dir():
            continue
        files = sorted(p for p in d.iterdir()
                       if p.is_file() and p.suffix == ".typ")
        for p in files:
            slug = p.stem
            n = count_lines(p)
            prev = existing.get((subject, slug), {})
            status = prev.get("status", "draft")
            reviewer = prev.get("reviewer", None)
            last_reviewed = prev.get("last_reviewed_at", None)
            lines.append(f"  - subject: {subject}")
            lines.append(f"    slug: {slug}")
            lines.append(f"    path: {subject}/{p.name}")
            lines.append(f"    lines: {n}")
            lines.append(f"    status: {yaml_escape(status)}")
            if reviewer is not None:
                lines.append(f"    reviewer: {yaml_escape(str(reviewer))}")
            if last_reviewed is not None:
                lines.append(f"    last_reviewed_at: {yaml_escape(str(last_reviewed))}")
            total += 1

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path.relative_to(root)} ({total} chapters)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
