#import "../template.typ": xref

= Image Segmentation <image-segmentation>

Segmentation assigns a label to every pixel in an image. The three main tasks are *semantic segmentation* (per-pixel class label), *instance segmentation* (per-pixel class + instance identity), and *panoptic segmentation* (unified semantic + instance). This chapter traces the evolution from fully convolutional networks through Mask R-CNN to the Segment Anything Model.

*See also:* #xref("computer-vision", "object-detection", label: "Object Detection") (proposal-based instance segmentation), #xref("computer-vision", "cnn-architectures", label: "CNN Architectures") (encoder backbones), #xref("computer-vision", "3d-vision", label: "3D Vision") (volumetric segmentation).

== Semantic Segmentation

=== Fully Convolutional Networks

*FCN* (Long, Shelhamer & Darrell, 2015) was the first end-to-end CNN for dense prediction. The key insight: replace fully connected layers with $1 times 1$ convolutions to produce dense predictions at reduced resolution, then upsample with *transposed convolution* (deconvolution) back to input resolution. FCN-32s upsamples from stride 32 in one step; FCN-16s/8s add skip connections from lower strides for sharper boundaries.

=== Encoder-Decoder: U-Net

*U-Net* (Ronneberger et al., 2015): symmetric encoder-decoder with *skip connections* between corresponding encoder and decoder layers. Originally for biomedical image segmentation; now the dominant architecture for any pixel-dense task (medical, satellite, industrial):

- *Encoder*: successive conv blocks + max pooling (stride 2 downsampling).
- *Bottleneck*: deepest representation.
- *Decoder*: transposed convolution (stride 2 upsampling) + concatenation of skip features + conv blocks.

Skip connections recover spatial detail lost during downsampling. U-Net++, Attention U-Net, and 3D U-Net are standard extensions.

=== DeepLab Family

*DeepLab* (Chen et al.): uses dilated convolutions to maintain resolution while growing the receptive field, and *Atrous Spatial Pyramid Pooling (ASPP)* to capture multi-scale context. ASPP applies dilated convolutions at rates $(6, 12, 18)$ in parallel, pools globally, and concatenates all outputs.

*DeepLabV3+* adds an encoder-decoder structure: ASPP as the encoder, a lightweight decoder that fuses encoder features with lower-level encoder features at stride 4. DeepLabV3+ with Xception backbone achieves 89.0 mIoU on PASCAL VOC.

=== PSPNet and Context Modules

*PSPNet* (Zhao et al., 2017): *Pyramid Pooling Module* pools features at four scales ($1 times 1$, $2 times 2$, $3 times 3$, $6 times 6$), upsamples each to original resolution, concatenates. Provides global context. Wins ILSVRC 2016 scene parsing.

== Instance Segmentation

=== Mask R-CNN

*Mask R-CNN* (He et al., 2017) extends Faster R-CNN with a parallel mask prediction head. For each RoI, a small FCN predicts a binary $28 times 28$ mask for each class. Key addition: *RoIAlign* replaces RoI pooling with bilinear interpolation at non-integer coordinates, eliminating the quantisation error that degraded mask quality.

The multi-task loss is:

$ cal(L) = cal(L)_"cls" + cal(L)_"box" + cal(L)_"mask" $

where $cal(L)_"mask"$ is binary cross-entropy per predicted mask. Masks are predicted for all classes; the predicted class selects which mask to use. Mask R-CNN is the baseline for all subsequent instance segmentation work.

=== SOLO and SOLOv2

*SOLO* (Wang et al., 2020): divide the image into a $S times S$ grid; predict a $S^2$ channel mask directly (each channel is the mask for instances centred in that cell). Simple, anchor-free, fully convolutional. SOLOv2 uses dynamic convolution: the mask is generated by convolving a feature map with instance-specific kernel weights.

=== Mask2Former and Masked Attention

*Mask2Former* (Cheng et al., 2022): universal architecture for semantic, instance, and panoptic segmentation. A pixel decoder (FPN-like) produces multi-scale features; a transformer decoder with $N$ queries outputs $N$ mask predictions; *masked attention* restricts each query to attend only within its predicted foreground mask region, dramatically accelerating convergence. Achieves state-of-the-art on all three segmentation benchmarks with a single model.

== Panoptic Segmentation

Panoptic segmentation (Kirillov et al., 2019) unifies *things* (countable instances: people, cars) and *stuff* (amorphous regions: sky, road). The *panoptic quality* metric:

$ "PQ" = underbrace((sum_("TP") "IoU"(p, g)) / (|"TP"| + 1/2 |"FP"| + 1/2 |"FN"| ), "recognition quality" times "segmentation quality"). $

*Panoptic FPN* merges FPN features for stuff (semantic head) and things (Mask R-CNN). *Panoptic-DeepLab* uses a bottom-up instance centroid approach.

== Transformers for Segmentation

=== SegFormer

*SegFormer* (Xie et al., 2021): hierarchical transformer encoder (Mix Transformer, MiT) producing multi-scale features; simple MLP decoder fuses features from all scales with positional-encoding-free attention. SegFormer-B5 achieves 51.8 mIoU on ADE20K.

=== SETR and Swin-based Segmentation

*SETR* (Zheng et al., 2021): encode the image with ViT-Large; decode with naive/PUP/MLA upsampling heads. Confirms that global context from ViT improves segmentation.

*Swin Transformer* (Liu et al., 2021) provides a hierarchical feature map ($1/4, 1/8, 1/16, 1/32$ resolution) compatible with FPN and thus with all existing detection/segmentation heads. Swin-based Mask2Former achieves 57.8 PQ on COCO panoptic.

== Segment Anything Model

*SAM* (Kirillov et al., 2023): a foundation model for segmentation. Architecture:
- *Image encoder*: ViT-H (or ViT-B/L variants) with MAE pre-training; produces $64 times 64$ image embeddings.
- *Prompt encoder*: encodes points, boxes, masks, and text as sparse + dense embeddings.
- *Mask decoder*: lightweight transformer with two-way attention; outputs three candidate masks + quality scores.

Trained on SA-1B: 11M images, 1.1B masks automatically annotated by SAM itself in a data-engine loop. SAM generalises to unseen domains (medical, satellite, microscopy) without fine-tuning. SAM 2 extends to video with a streaming memory architecture.

== Video Object Segmentation

*Semi-supervised VOS*: given the first-frame mask, propagate to subsequent frames. DeAOT, XMem use memory queues for long-term propagation.

*Unsupervised VOS*: no first-frame mask; use motion (optical flow) or saliency cues.

*Referring segmentation*: segment the object described by a language query. LAVT, ReLA combine BERT text features with vision features for grounded segmentation.

== Medical Image Segmentation

Medical segmentation has unique challenges: 3D volumes (CT, MRI), limited labelled data, large class imbalance, fine-grained boundaries.
- *nnU-Net* (Isensee et al., 2021): self-configuring U-Net that automatically adapts architecture and training to the dataset. Baseline that wins most medical segmentation challenges.
- *TransUNet, SwinUNet*: hybrid CNN-transformer U-Nets for improved global context.
- *Dice loss*: $cal(L)_"Dice" = 1 - (2 |P inter G|) / (|P| + |G|)$. Better than cross-entropy for imbalanced foreground/background.

== Benchmarks

#table(
  columns: 4,
  [*Model*], [*Task*], [*Dataset*], [*Score*],
  [DeepLabV3+], [Semantic], [VOC 2012], [89.0 mIoU],
  [SegFormer-B5], [Semantic], [ADE20K], [51.8 mIoU],
  [Mask R-CNN], [Instance], [COCO], [37.1 mask AP],
  [Mask2Former], [Instance], [COCO], [50.1 mask AP],
  [Mask2Former], [Panoptic], [COCO], [57.8 PQ],
  [SAM], [Interactive], [SA-1B], [generalises zero-shot],
)

== Further Reading

- Long, J., Shelhamer, E., & Darrell, T. (2015). Fully convolutional networks for semantic segmentation. _CVPR_.
- Ronneberger, O., Fischer, P., & Brox, T. (2015). U-Net. _MICCAI_.
- He, K. et al. (2017). Mask R-CNN. _ICCV_.
- Chen, L.-C. et al. (2018). DeepLabV3+. _ECCV_.
- Cheng, B. et al. (2022). Masked-attention mask transformer for universal image segmentation. _CVPR_.
- Kirillov, A. et al. (2023). Segment Anything. _ICCV_.
